### ISSUE TITLE
Bug: language_helper not POSIX compatible / crashes

### ISSUE THREAD

**Issue by JaGennis** [hochschule-darmstadt/openartbrowser#107]
The script language_helper.py uses the Windows file path backslash instead of the POSIX slash, is therefore not POSIX compatible and crashes on the server.  
This can be avoided by testing the scripts on the server before merging.
Also os.path should be avoided in favour of pathlib.

**Comment by jschurse** [comment]
Thank you for your Fix!

**Comment by tilomi** [comment]
I did the crawl on a seperate branch https://github.com/hochschule-darmstadt/openartbrowser/tree/multilang+iconclass  We have to look up if anything is missing from there in the staging branch
