### ISSUE TITLE
Find and add a fitting wikipedia abstract for every entity if possible

### ISSUE THREAD

**Issue by EeveesEyes** [hochschule-darmstadt/openartbrowser#11]
**Is your feature request related to a problem? Please describe.**
It would be nice to have a short description text for every artist, artwork, etc. Due to the tremendous amount of available data on wikipedia and their 'abstract' feature, we suggest to use this additional to the information given by the wikidata-data-set. 

**Why do you want this feature? What goals should be achieved**
The goal is to provide more information about the depicted object to users.

**Describe the solution you'd like**
- Find fitting wikipedia article
- Get abstracts from fitting wikipedia article
- Pass abstract to elasticsearch backend
- Include abstracts to every component in the frontend requested.
This list needs to be discussed:
  + ARTIST
  + ARTWORK
  + GENRE
  + LOCATION
  + MATERIAL  //do we need to tell the user what wood and oil paints are?
  + MOVEMENT
  + MOTIF

**Describe acceptance criteria**
On every wikidata-data-set, which provides wikipedia links, a abstract is displayed on its oAB site.

**Describe alternatives you've considered**
No alternatives

**What effects does your proposed solution have**
The extraction of the abstract requires a modification on the `ArtOntologyCrawler.py`, the elastic search data-set, the frontend-model and every required component.

**Additional context**
FYI: Wikipedia calls the short text of an article 'extract', we call it 'abstract'.
Example:
![tmp](https://user-images.githubusercontent.com/28682931/67945964-87bbf900-fbe0-11e9-92d1-59b601b12d9f.png)

**Comment by jschurse** [comment]
This feature has now been integrated and deployed to the staging server.
But it's currently not working because the ETL Job is still running.
