### ISSUE TITLE
Redirect to fitting language version

### ISSUE THREAD

**Issue by jschurse** [hochschule-darmstadt/openartbrowser#111]
**Is your feature request related to a problem? Please describe.**
We supply the language specific versions of the app via an URL Slug eg.
openartbrowser.org/en/ for the english version openartbrowser.org/de/ for the german version.
If a user calls just openartbrowser.org/ a redirect to the most fitting language version is needed

**Why do you want this feature? What goals should be achieved**
The user should be redirected to the language specific version of openartbrowser most fitting to the language settings of the browser.

**Describe the solution you'd like**
A simple redirect depending on the accept-language header of the browsers request.

**Describe acceptance criteria**
- a german webbrowser is redirected to the /de/ slug
- an english webbrowser is redirected to the /en/ slug
- a japanese webbrowser is redirected to the /en/ slug

**Describe alternatives you've considered**
let the use decide which version should be used. But that doesn't simplify it. The user would need to select for himself which is an additional clickt.

**What effects does your proposed solution have**
If we add additional language versions we need to update this script.

**Comment by xcaverxiii** [comment]
The JS code for the https://openartbrowser.org/ index.html should look like:
```
var language = navigator.language || navigator.userLanguage; 
language = language.toLowerCase().split('-')[0];

window.location.href = window.location.href + "/" + language;
```

**Comment by jschurse** [comment]
Nginx supports scripting via Lua. So we could run a server side script which knows what languages we support by scanning the directory for the language specific builds (eg. './de', './en', './fr')
I found such a [script here](https://github.com/fghibellini/nginx-http-accept-lang/blob/master/lang.lua).

This would serve the same purpose as doing it in php as mentioned by you @xcaverxiii but we wouldn't collect another language dependency.

**Comment by jschurse** [comment]
This is now being solved by using the JS Code in an index.html file.
If the redirect did not match any available language an additional redirect to the english version is returned by the webserver:

```
location ~ ^/([a-z][a-z])/ {
    try_files $uri $uri/ /$1/index.html @redirect;
}

location @redirect {
    return 301 " /en";
}
```
