### ISSUE TITLE
Use 'Also known as' field to find artists and other entities

### ISSUE THREAD

**Issue by EeveesEyes** [hochschule-darmstadt/openartbrowser#114]
**Is your feature request related to a problem? Please describe.**
Currently the user can't find an entity if he knows it under a different name than the english one. For instance, some artists' original names are completely different from their displayed english version.
Example: https://www.wikidata.org/wiki/Q130777
*Kazimir Malevich
*Kasimir Sewerinowitsch Malewitsch
*Казимир Северинович Малевич

**Why do you want this feature? What goals should be achieved**
To improve the users' ability to find what they already know they should be able to find the entity they mean in the most possible ways.

**Describe the solution you'd like**
Add the 'Also known as' field to the crawling and search process

**Describe acceptance criteria**
Alternative names can be used to find artists, artworks and such.

**What effects does your proposed solution have**
This would eventually result in more false positives in the search results.

**Additional context**
-None-

**Comment by BernhardHumm** [comment]
With the multi-language feature, you will not search in English, but in the language of your choice. 

Still, this improvement is a good idea. The “also known as” field should be selected with a language identifier and only searchable in the respective language.

 

           Bernhard Humm

 

Von: Adrian Kailus [mailto:notifications@github.com] 
Gesendet: Donnerstag, 5. Dezember 2019 11:42
An: hochschule-darmstadt/openartbrowser <openartbrowser@noreply.github.com>
Cc: Subscribed <subscribed@noreply.github.com>
Betreff: [hochschule-darmstadt/openartbrowser] Use 'Also known as' field to find artists and other entities (#114)

 

Is your feature request related to a problem? Please describe.
Currently the user can't find an entity if he knows it under a different name than the english one. For instance, some artists' original names are completely different from their displayed english version.
Example: https://www.wikidata.org/wiki/Q130777
*Kazimir Malevich
*Kasimir Sewerinowitsch Malewitsch
*Казимир Северинович Малевич

Why do you want this feature? What goals should be achieved
To improve the users' ability to find what they already know they should be able to find the entity they mean in the most possible ways.

Describe the solution you'd like
Add the 'Also known as' field to the crawling and search process

Describe acceptance criteria
Alternative names can be used to find artists, artworks and such.

What effects does your proposed solution have
This would eventually result in more false positives in the search results.

Additional context
-None-

**Comment by EeveesEyes** [comment]
Duplicate of #201
