### ISSUE TITLE
Switch from old elasticsearch index to new one

### ISSUE THREAD

**Issue by tilomi** [hochschule-darmstadt/openartbrowser#119]
**Is your feature request related to a problem? Please describe.**
The elasticsearch index shouldn't be updated. Instead it should just be replaced by a new one.

**Why do you want this feature? What goals should be achieved**
The elasticsearch index on the server should be swapped not updated like it's done currently.

**What effects does your proposed solution have**
No corrupt data after refactorings.

**Comment by BernhardHumm** [comment]
It is important that this solution will not result in a downtime of the life system!

 

           Bernhard Humm

 

 

Von: Tilo Michel [mailto:notifications@github.com] 
Gesendet: Donnerstag, 5. Dezember 2019 12:35
An: hochschule-darmstadt/openartbrowser <openartbrowser@noreply.github.com>
Cc: Subscribed <subscribed@noreply.github.com>
Betreff: [hochschule-darmstadt/openartbrowser] Switch from old elasticsearch index to new one (#119)

 

Is your feature request related to a problem? Please describe.
The elasticsearch index shouldn't be updated. Instead it should just be replaced by a new one.

Why do you want this feature? What goals should be achieved
The elasticsearch index on the server should be swapped not updated like it's done currently.

What effects does your proposed solution have
No corrupt data after refactorings.

**Comment by tilomi** [comment]
Merged on staging tested locally should also work on the servers.
