### ISSUE TITLE
Implement logging functionality for both backend and client

### ISSUE THREAD

**Issue by jschurse** [hochschule-darmstadt/openartbrowser#132]
**Is your feature request related to a problem? Please describe.**
Wen want to run the ETL process unsupervised periodically without the need for a developer to check after each run, if errors did occure.

On the same page we have the client which is being run by the clients webbrowser. If an error occures it is being logged to the browsers JS console but the error does normally not reach the developer.

**Why do you want this feature? What goals should be achieved**
If an error occurs either on the ETL process or at runtime by the client it should be protocoled in such a manner that developers have access to the logs and in the best case are actively being notified when something is wrong.
Only then we can solve these problems.

**Describe the solution you'd like**
A logging system in which both the ETL process and the Angular Client log notifications, warnings and errors.
I propose to use the [Graylog](https://www.graylog.org/) logging Server. It's an open source solution which we can self host. 
It is a proven piece of software with an universal logging interface via the [GELF](https://docs.graylog.org/en/3.1/pages/gelf.html). 
It integrates well with [python](https://github.com/severb/graypy) and there are [implementations for angular](https://github.com/frnd/angular-graylog2/blob/master/lib/angular-graylog2.js) as well.

**Describe acceptance criteria**
Any error thrown in the ETL process and client are being logged to a single service.

**Describe alternatives you've considered**
We could use a hosted service that provides the same goals.

**Comment by jschurse** [comment]
Since Graylog has dependencies like Elasticsearch and Mongodb, I propose to run it dockerized as described here: https://docs.graylog.org/en/3.1/pages/installation/docker.html

**Comment by lbucas** [comment]
So Graylog logging will not be implemented?
