### ISSUE TITLE
Wikipedia abstracts only in english

### ISSUE THREAD

**Issue by jschurse** [hochschule-darmstadt/openartbrowser#148]
**Is your feature request related to a problem? Please describe.**
The abstracts we get from Wikipedia are only in english.
It should be displayed in the language of the application, if no abstract for this version exists no abstract should be displayed.
![image](https://user-images.githubusercontent.com/12964877/70699823-0456f280-1cca-11ea-9ea0-c4e2b408b24e.png)

**Comment by tilomi** [comment]
Multilanguage is not implemented for Wikipedia at the moment. This has to be done in the ArtOntologyCrawler.py similar to the labels

**Comment by istthabel** [comment]
fixed and merged #190
