### ISSUE TITLE
Generate .json-files directly in ArtOntologtCrawler.py instead invoking the js-scripts

### ISSUE THREAD

**Issue by JaGennis** [hochschule-darmstadt/openartbrowser#15]
**Is your feature request related to a problem? Please describe.**
This feature request is related to issue [8](https://github.com/hochschule-darmstadt/openartbrowser/issues/8).

**Why do you want this feature? What goals should be achieved**
To skip the call of multiple js-scripts.

**Describe the solution you'd like**
The .json-files get generated similar to the .csv-files in ArtOntologtCrawler.py.

**Describe acceptance criteria**
If ArtOntologyCrawler generates the same .json-files like the js-scripts.

**Describe alternatives you've considered**
Additional python script to convert all .csv-files to .json-files.

**What effects does your proposed solution have**
It makes the "script_*.js"-scripts redundant.j

**Additional context**
...

**Comment by BernhardHumm** [comment]
Ich finde die beschriebene Alternative (Additional python script to convert all .csv-files to .json-files) architektonisch die sauberere Lösung (separation of concerns).

Diese Konversions-Routine kann generisch programmiert werden (d.h. für alle *.csv Dateien) und kann dann n mal aufgerufen werden.

 

 

Viele Grüße

           Bernhard Humm

 

------------------------------------

Prof. Dr. Bernhard Humm

Geschäftsführender Direktor, Institut für angewandte Informatik Darmstadt (aiDa)

Vorsitzender Promotionsausschuss, Promotionszentrum Angewandte Informatik

h_da Hochschule Darmstadt - University of Applied Sciences, fbi Fachbereich Informatik 

Schöfferstr. 8b, D-64295 Darmstadt

Tel: +49 6151 16 38494, Fax: +49 6151 16 38935, Home Office: +49 6031 6714726

 <mailto:bernhard.humm@h-da.de> bernhard.humm@h-da.de, https://fbi.h-da.de/personen/personenseiten/bernhard-humm/

 

 

Von: JaGennis [mailto:notifications@github.com] 
Gesendet: Donnerstag, 31. Oktober 2019 12:47
An: hochschule-darmstadt/openartbrowser <openartbrowser@noreply.github.com>
Cc: Subscribed <subscribed@noreply.github.com>
Betreff: [hochschule-darmstadt/openartbrowser] Generate .json-files directly in ArtOntologtCrawler.py instead invoking the js-scripts (#15)

 

Is your feature request related to a problem? Please describe.
This feature request is related to issue 8 <https://github.com/hochschule-darmstadt/openartbrowser/issues/8> .

Why do you want this feature? What goals should be achieved
To skip the call of multiple js-scripts.

Describe the solution you'd like
The .json-files get generated similar to the .csv-files in ArtOntologtCrawler.py.

Describe acceptance criteria
If ArtOntologyCrawler generates the same .json-files like the js-scripts.

Describe alternatives you've considered
Additional python script to convert all .csv-files to .json-files.

What effects does your proposed solution have
It makes the "script_*.js"-scripts redundant.j

Additional context
...

**Comment by JaGennis** [comment]
Ich habe den Code jetzt so umgeschrieben, dass in den verschiedenen Funktionen nicht mehr direkt die *.csv's generiert werden, sondern eine Liste von Dictionaries. Diese kann dann der Funktion `generate_csv` und / oder der Funktion `generate_json` übergeben werden, um die entsprechenden Dateien zu erzeugen. Durch das Trennen von csv-Generierung und Crawling wird der Crawler-Code sowie das `run_all.sh`-Shell-Skript übersichtlicher und es könnten in Zukunft auch andere Dateiformate erzeugt werden. Beide Funktionen kann ich aber auch noch in ein anderes Python-Skript, dessen Funktionen dann im Crawler importiert werden, auslagern falls gewünscht. Die Änderungen sind im Branch [feature/15_json_in_crawler](https://github.com/hochschule-darmstadt/openartbrowser/tree/feature/15_json_in_crawler) zu sehen.

**Comment by BernhardHumm** [comment]
gut

 

 

Viele Grüße

           Bernhard Humm

 

 

Von: JaGennis [mailto:notifications@github.com] 
Gesendet: Montag, 4. November 2019 14:25
An: hochschule-darmstadt/openartbrowser <openartbrowser@noreply.github.com>
Cc: Humm, Bernhard, Prof. Dr. <bernhard.humm@h-da.de>; Comment <comment@noreply.github.com>
Betreff: Re: [hochschule-darmstadt/openartbrowser] Generate .json-files directly in ArtOntologtCrawler.py instead invoking the js-scripts (#15)

 

Ich habe den Code jetzt so umgeschrieben, dass in den verschiedenen Funktionen nicht mehr direkt die *.csv's generiert werden, sondern eine Liste von Dictionaries. Diese kann dann der Funktion generate_csv und / oder der Funktion generate_json übergeben werden, um die entsprechenden Dateien zu erzeugen. Durch das Trennen von csv-Generierung und Crawling wird der Crawler-Code sowie das run_all.sh-Shell-Skript übersichtlicher und es könnten in Zukunft auch andere Dateiformate erzeugt werden. Beide Funktionen kann ich aber auch noch in ein anderes Python-Skript, dessen Funktionen dann im Crawler importiert werden, auslagern falls gewünscht. Die Änderungen sind im Branch feature/15_json_in_crawler <https://github.com/hochschule-darmstadt/openartbrowser/tree/feature/15_json_in_crawler>  zu sehen.

**Comment by tilomi** [comment]
Resolved in pullrequest #39
