### ISSUE TITLE
Multiple ui bugs

### ISSUE THREAD

**Issue by jschurse** [hochschule-darmstadt/openartbrowser#150]
**Is your feature request related to a problem? Please describe.**

Multiple ui bugs currently exist:

The arrow next to the artwork label lost some margin:
Is:
![image](https://user-images.githubusercontent.com/12964877/70700115-7af3f000-1cca-11ea-8ba1-4cdb9b7f584b.png)
Should be:
![image](https://user-images.githubusercontent.com/12964877/70700158-8d6e2980-1cca-11ea-9832-cce4c2683875.png)

After clicking the arrow at "Common Tags" the arrow disappears:
https://cai-artbrowserstaging.fbi.h-da.de/de/artwork/Q29530

**Comment by xcaverxiii** [comment]
More Problems:
![image](https://user-images.githubusercontent.com/25961416/70705273-0aea6780-1cd4-11ea-8993-2777bbbbecf5.png)

Set Image by Artist, Genre, Movement, etc before Content on mobile.

Make Slider icons bigger on mobile.
![image](https://user-images.githubusercontent.com/25961416/70705606-9e239d00-1cd4-11ea-877c-e1160df1b4da.png)

**Comment by JamieArmstrongArndt** [comment]
@xcaverxiii I was wondering if it would make sense to allign the abstract information as justification (Blocksatz). I hope it is just a small change in the sass-file (text-allign: justify). Would you mind checking this out, too, while you are at it?

**Comment by xcaverxiii** [comment]
@JamieArmstrongArndt 
Do you mean something like that?
![image](https://user-images.githubusercontent.com/25961416/70851685-8a289880-1e98-11ea-8a36-a7c5b53f29f0.png)

**Comment by xcaverxiii** [comment]
Problems like this:
> ![image](https://user-images.githubusercontent.com/25961416/70705273-0aea6780-1cd4-11ea-8993-2777bbbbecf5.png)

Can be solved with this issue #167
