### ISSUE TITLE
Enable middle mouse click and right click on routed html elements 

### ISSUE THREAD

**Issue by EeveesEyes** [hochschule-darmstadt/openartbrowser#155]
**Is your feature request related to a problem? Please describe.**
Currently it is not possible to open a routed element in a new tab by middle mouse click (example element in app-carousel)

**Why do you want this feature? What goals should be achieved**
Enable 'advanced' navigation.

**Describe the solution you'd like**
None

**Describe acceptance criteria**
New tab can be opened by middle click

**Describe alternatives you've considered**
None

**What effects does your proposed solution have**
Should only effect router items.

**Additional context**
None

**Comment by mauamy** [comment]
I created a branch ([bug/155/item_link_behaviour](https://github.com/hochschule-darmstadt/openartbrowser/tree/bug/155/item_link_behaviour)) and added a fix for the carousel items.
I do not want to have the same fix for this bug in different branches, the same fix will be applied to timeline items as soon as the timeline feature is on staging.
