### ISSUE TITLE
Install matomo on our server

### ISSUE THREAD

**Issue by lbucas** [hochschule-darmstadt/openartbrowser#159]
**Is your feature request related to a problem? Please describe.**
We want to use matomo as usage analytics tool. The open source software must be installed on our server.

**Why do you want this feature? What goals should be achieved**
With a self-hosted usage analytics software, we are in full control of the processed data and do not have the same data privacy issues as with Google Analytics.

**Describe the solution you'd like**
Matomo can be installed on a PHP/MySQL stack. Alternatively there is a dockerized version. I would suggest using the prod server.
 
**Describe acceptance criteria**
The service is accessible on our server. Credentials shall be stored in NextCloud.
 
**Describe alternatives you've considered**
No usage analytics or Google Analytics.

**What effects does your proposed solution have**
Additional software on the server.

**Additional context**
Latest build I tested on my machine: https://builds.matomo.org/matomo.zip
Github: https://github.com/matomo-org/matomo
As docker container: https://github.com/matomo-org/docker

**Comment by lbucas** [comment]
Additional requirement: If the docker container is used, the MySql database should be accessible from within the server.

**Comment by lbucas** [comment]
@jschurse die you find the time to so this yet? I could do it too, but I would need the server credentials.

**Comment by jschurse** [comment]
Hey,
Yeah I started with this issue on the weekend.
I asked Bernhard Humm, if we could use the subdomain
analytics.openartbrowser.org to have an endpoint under which we can deliver
our analytics tool.
I'm currently awaiting a response.

Lucas Bergmann <notifications@github.com> schrieb am Mo., 16. Dez. 2019,
09:53:

**Comment by jschurse** [comment]
It's served now via a reverse proxy under the endpoint: 
https://openartbrowser.org/api/analytics/
