### ISSUE TITLE
Add language switch to the client

### ISSUE THREAD

**Issue by xcaverxiii** [hochschule-darmstadt/openartbrowser#16]
**Is your feature request related to a problem? Please describe.**
How can i switch the language without changing the url directy?

**Why do you want this feature? What goals should be achieved**
A button to see the existing languages and change them.

**Describe the solution you'd like**
Add a droptown menu to the navigation menu. With this dropdown it is possible to change the language. All existing lanugage translations are shown there.

**Describe acceptance criteria**
I can change the language to all existing translations, without changing the url directly.

**Describe alternatives you've considered**

**What effects does your proposed solution have**
Mutli language support must be implemented before. Both client side and server side.

**Additional context**
#9

**Comment by jschurse** [comment]
> **Is your feature request related to a problem? Please describe.**
> How can i switch the language without changing the url directy?
> 
> **Why do you want this feature? What goals should be achieved**
> A button to see the existing languages and change them.
> 
> **Describe the solution you'd like**
> Add a droptown menu to the navigation menu. With this dropdown it is possible to change the language. All existing lanugage translations are shown there.
> 
> **Describe acceptance criteria**
> I can change the language to all existing translations, without changing the url directly.
> 
> **Describe alternatives you've considered**
> 
> **What effects does your proposed solution have**
> Mutli language support must be implemented before. Both client side and server side.
> 
> **Additional context**
> #9

To clear up how exactly a proposed implementation would look could you please elaborate on how the language switcher is being implemented?
Would we serve the different languages from different folders so eg. 
http://openartbrowser.org/de/
http://openartbrowser.org/en/
http://openartbrowser.org/fr/
Wheres we compile and deploy the app configured for each of our supported languages? 
So it would just be a list of links to the other versions?

**Comment by xcaverxiii** [comment]
> To clear up how exactly a proposed implementation would look could you please elaborate on how the language switcher is being implemented?
> Would we serve the different languages from different folders so eg.
> http://openartbrowser.org/de/
> http://openartbrowser.org/en/
> http://openartbrowser.org/fr/
> Wheres we compile and deploy the app configured for each of our supported languages?
> So it would just be a list of links to the other versions?

Each translated side is in a separate folder. To reach one of these, we would use the links like you has written. 
The language switcher would just change the language parameter in the url, so that the current page will be shown in another language. 

The main url http://openartbrowser.org/ will in the first time just redirect to a specfic translation, for example to the englisch one. 

I hasn´t seen any app configured that can and must be changed after compile the project for each lanugage. Or am I wrong?

**Comment by xcaverxiii** [comment]
World icon is added to the header navbar as language switcher.

Switcher works if builds in multiple languages are deployed.
