### ISSUE TITLE
Change YT embed links to enhanced data privacy mode

### ISSUE THREAD

**Issue by lbucas** [hochschule-darmstadt/openartbrowser#164]
**Is your feature request related to a problem? Please describe.**
The embedded videos do not run in the data privacy mode and write cookies.

**Why do you want this feature? What goals should be achieved**
This is a data privacy issue and should be resolved.

**Describe the solution you'd like**
This requires a small change to the embed link.

**Describe acceptance criteria**
Videos run in data privacy mode.

**What effects does your proposed solution have**
Small changes to the ETL script

**Additional context**
https://support.google.com/youtube/answer/171780?hl=de

**Comment by jschurse** [comment]
Has been merged
