### ISSUE TITLE
Continuous deployment

### ISSUE THREAD

**Issue by JamieArmstrongArndt** [hochschule-darmstadt/openartbrowser#18]
**Is your feature request related to a problem? Please describe.**
The changes to code currently needs to be upload manually and does not support any features to test the reliablity of new features or commits. 

**Why do you want this feature? What goals should be achieved**
We want to automate the process of deploying changes to staging (and later to production) in order to reduce manual effort.

**Describe the solution you'd like**
Every pull request should be automatically checked by our test suites as an additional requirement in the review process to ensure, that only functional code is deployed (connected to Continuous Integration)

**Describe acceptance criteria**
When a merge pull request is automatically deployed on the staging system.

**Describe alternatives you've considered**
And alternative we considered is Jenkins which also provides CI/CD capabilities.

**Comment by mxxbe** [comment]
#41 solves this issue once merged

**Comment by mxxbe** [comment]
Has been merged into staging, so I will close this
