### ISSUE TITLE
Small and Medium sized images are dependent on fix resolutions 

### ISSUE THREAD

**Issue by EeveesEyes** [hochschule-darmstadt/openartbrowser#180]
**Is your feature request related to a problem? Please describe.**
If an image is available in another format than .tif or .tiff we have two hard coded resolutions 256px and 512px. There is no check whether these resolutions exist after all. Furthermore, in case of a .tif or .tiff file, we don't use downscaled versions of the file, even tho they exist.
This is an example, where a .tif has other downscaled versions than 256px or 512px.
[Q19161184](https://commons.wikimedia.org/wiki/File:BMVB_-_Pedro_Durán_-_Entrada_de_catedral_gòtica_(Tarragona)_-_1083.tif)

**Why do you want this feature? What goals should be achieved**
If an downscaled version of the file is available, we should use it. Furthermore we should check somehow if these urls exist, currently we trust in generated urls.

**Describe the solution you'd like**
The current logic for this happens in the data.service.ts in the frontend. Probably this could be moved to the crawling process.

**What effects does your proposed solution have**
This could have an effect on the runtime of the crawler.

**Comment by EeveesEyes** [comment]
[Johan Christian Jansson](https://cai-artbrowserstaging.fbi.h-da.de/en/artist/Q5879634) is completely broken due to this and other missing data

**Comment by mauamy** [comment]
Related: #250

**Comment by tilomi** [comment]
From the current status of #250 i would assume that scaling jpgs doesn't seem to be a problem with the already used method however when it comes to tifs this is a problem. I asked on their ticke system for a best practice solution for this problem. Maybe this helps also in this case.

**Comment by EeveesEyes** [comment]
Will be fixed by #250 (hopefully(maybe))
