### ISSUE TITLE
Video indication not always shown

### ISSUE THREAD

**Issue by EeveesEyes** [hochschule-darmstadt/openartbrowser#185]
**Issue description**
Even tho there is a video for an element, it is not always shown

**Steps to reproduce the issue**

1.  Visit [artist Q7814](https://cai-artbrowserstaging.fbi.h-da.de/en/artist/Q7814)
2. Open More section

**What's the expected result?**

- A video indicator is shown

**What's the actual result?**

- no video indicator is shown

**Additional details / screenshot**

- Only the video component knows if a video is found. 

**Suggested Solution**

- The video component emits a EventEmitter in case a video was found. The implementing component listens to the event.

**Comment by jschurse** [comment]
The Problem does also occur on this page: 
https://cai-artbrowserstaging.fbi.h-da.de/de/movement/Q3773653

**Comment by mxxbe** [comment]
Another occurence: 
https://cai-artbrowserstaging.fbi.h-da.de/de/artwork/Q21586301

We have a video but no indicator

**Comment by EeveesEyes** [comment]
It happens on all pages where a "second level" video was found. :)
