### ISSUE TITLE
Multimedia label in front of YouTube logo

### ISSUE THREAD

**Issue by mxxbe** [hochschule-darmstadt/openartbrowser#186]
**Is your feature request related to a problem? Please describe.**
Not exactly a problem - see below.

**Why do you want this feature? What goals should be achieved**
Currently the YouTube logo is just displayed context-free above the "more" toggle.
I think it would be nice to have a label "multimedia" or something similar in front of it, to integrate the button into the existing design seamlessly.

**Describe the solution you'd like**
It could look something like this, just layouted/spaced correctly:

![image](https://user-images.githubusercontent.com/22763390/71165051-72626300-2250-11ea-8fe9-ab7295d4c9a7.png)

Of course we wouldn't display the label at all if we dont have multimedia entries for the selected entity.

**What effects does your proposed solution have**
The design wouldn't be disrupted by the logo. 
Also if we want to integrate more multimedia in the future, we can just extend the list of logos.

**Additional context**
An optional feature would be, that a click on the button toggles "more" and scrolls the viewport to the first video (or generally multimedia entry of the clicked category).

**Comment by BernhardHumm** [comment]
No!

We decided to place the icon before the “more” label.

 

           Bernhard Humm

 

------------------------------------

 

 

 

Von: Maximilian Belling [mailto:notifications@github.com] 
Gesendet: Donnerstag, 19. Dezember 2019 11:18
An: hochschule-darmstadt/openartbrowser <openartbrowser@noreply.github.com>
Cc: Subscribed <subscribed@noreply.github.com>
Betreff: [hochschule-darmstadt/openartbrowser] Multimedia label in front of YouTube logo (#186)

 

Is your feature request related to a problem? Please describe.
Not exactly a problem - see below.

Why do you want this feature? What goals should be achieved
Currently the YouTube logo is just displayed context-free above the "more" toggle.
I think it would be nice to have a label "multimedia" or something similar in front of it, to integrate the button into the existing design seamlessly.

Describe the solution you'd like
It could look something like this, just layouted/spaced correctly:

 <https://user-images.githubusercontent.com/22763390/71165051-72626300-2250-11ea-8fe9-ab7295d4c9a7.png> 

Of course we wouldn't display the label at all if we dont have multimedia entries for the selected entity.

What effects does your proposed solution have
The design wouldn't be disrupted by the logo.
Also if we want to integrate more multimedia in the future, we can just extend the list of logos.

Additional context
An optional feature would be, that a click on the button toggles "more" and scrolls the viewport to the first video (or generally multimedia entry of the clicked category).
