### ISSUE TITLE
Knowledge import to wiki

### ISSUE THREAD

**Issue by istthabel** [hochschule-darmstadt/openartbrowser#19]
**Is your feature request related to a problem? Please describe.**
All knowledge is currently located at 3rd party file server and cumbersome to access.

**Why do you want this feature? What goals should be achieved**
1) We want to create a structure to centralize all documentation in the wiki.
2) We want to link the files from their current location to the wiki.

**Describe the solution you'd like**
We want a wiki structure that is easy to navigate with all existing knowledge.

**Describe acceptance criteria**
1) Important information can be found in the wiki in less than 30 seconds.
2) All existing knowledge can be found in the wiki.

**Describe alternatives you've considered**
There is no alternative.

**What effects does your proposed solution have**
Easy to find information makes the actual work more comfortable.

**Additional context**
None

**Comment by jschurse** [comment]
Information was imported :)
