### ISSUE TITLE
Improve performance of search suggestions/completion

### ISSUE THREAD

**Issue by mauamy** [hochschule-darmstadt/openartbrowser#195]
**Is your feature request related to a problem? Please describe.**
Displaying the search suggestions when typing into the search bar takes (too) long.

**Why do you want this feature? What goals should be achieved**
Showing the search suggestion too late leads to a very intuitive experience for the user.

**Describe the solution you'd like**
The search suggestion should be display more or less instantly.

**Describe acceptance criteria**
The search suggestions are displayed fast enough to not irritate the user.

**Comment by JamieArmstrongArndt** [comment]
Can be closed due to performance improvement with reduction of result size.

Also discussed in https://github.com/hochschule-darmstadt/openartbrowser/issues/156.
