### ISSUE TITLE
Search finds the language identifier 

### ISSUE THREAD

**Issue by EeveesEyes** [hochschule-darmstadt/openartbrowser#196]
**Issue description**
The search finds the language identifier which is added to the label in case a fitting name is not available ( e.g. (French) ).

**Steps to reproduce the issue**

1.  e.g. Type 'ren'

**What's the expected result?**

- Hits don't contain '( French )' are displayed

**What's the actual result?**

- Hits containing '( French )' are displayed

**Additional details / screenshot**

- ![tmp](https://user-images.githubusercontent.com/28682931/71173332-bb231780-2262-11ea-9a67-96ffa7050a3a.png)

**Suggested Solution**

- ?

**Comment by BernhardHumm** [comment]
Solution: 

In ETL, do not add language in parenthesis when filling in missing label from other language. 

 

           Bernhard Humm

 

------------------------------------

 

 

Von: Adrian Kailus [mailto:notifications@github.com] 
Gesendet: Donnerstag, 19. Dezember 2019 13:24
An: hochschule-darmstadt/openartbrowser <openartbrowser@noreply.github.com>
Cc: Subscribed <subscribed@noreply.github.com>
Betreff: [hochschule-darmstadt/openartbrowser] Search finds the language identifier (#196)

 

Issue description
The search finds the language identifier which is added to the label in case a fitting name is not available ( e.g. (French) ).

Steps to reproduce the issue

1.	e.g. Type 'ren'

What's the expected result?

*	Hits don't contain '( French )' are displayed

What's the actual result?

*	Hits containing '( French )' are displayed

Additional details / screenshot

*	 <https://user-images.githubusercontent.com/28682931/71173332-bb231780-2262-11ea-9a67-96ffa7050a3a.png> 

Suggested Solution

*	?

**Comment by jschurse** [comment]
@BaderChouaib you wrote much of the language separation code. Could you please have a look at this?

**Comment by BaderChouaib** [comment]
This issue was dealt with by merging  #194 into the staging branch on the day when this issue was created. I wasnt aware that an explicit bug issue existed for this likely because we modified the root cause (removal of language identifiers) as an enhancement feature in accordance with Prof. Humm

This issue can be closed
