### ISSUE TITLE
duplicated movement tag 'Impressionism' on artist Q39931

### ISSUE THREAD

**Issue by mauamy** [hochschule-darmstadt/openartbrowser#197]
Issue description
The movement 'Impressionism' is duplicated on artist **Q39931** for all languages.

Steps to reproduce the issue

1.  Go to the artist [Q39931](https://cai-artbrowserstaging.fbi.h-da.de/it/artist/Q39931)
2. click on more
3. check the movement tags

What's the expected result?

- each movement should be displayed only once

What's the actual result?

- 'Impressionism' is displayed twice.

Additional details / screenshot

![](https://user-images.githubusercontent.com/28662686/71173581-68962b00-2263-11ea-8ce1-b9d44cae971e.png)

Suggested Solution

- First check why this is happening and then discuss further solutions.

**Comment by tilomi** [comment]
I think this is resolved by now?

**Comment by mauamy** [comment]
Yes, this looks good to me.
