### ISSUE TITLE
Name refactoring for generated ETL files

### ISSUE THREAD

**Issue by tilomi** [hochschule-darmstadt/openartbrowser#21]
**Is your feature request related to a problem? Please describe.**
Because of historical reasons file names for the same topics don't match in their name. For example creators.csv is transformed to artists.json and depicts.csv is transformed to objects.json. To enhance 
understandability it is necessary to use just one name for each subject. For example creators.csv could be named to artists.csv. Also the final .json output file "master_flat_rank.json" could be renamed to ArtOntology.json for example.

**Why do you want this feature? What goals should be achieved**
Better understandibility of dependencies in the intermediate files

**Describe the solution you'd like**
Intermediate steps which contain similar subjects contain the subject in their name. No more synonyms like artists/creators or depicts/objects.

**Describe acceptance criteria**
See solution

**Describe alternatives you've considered**
In general we could replace certain names with new ones. This has to be discussed. We would prefer to use the same names as shown on the website.

drawings.csv 
sculptures.csv
paintings.csv
artworks.csv -> artworks.json -> artworks_rank.json
genres.csv -> genres.json -> genres_rank.json
movements.csv -> movements.json -> movements_rank.json
materials.csv -> materials.json -> materials_rank.json
depicts.csv -> objects.json -> objects_rank.json
creators.csv -> artists.json -> artists_rank.json
locations.csv ->locations.json -> locations_rank.json

All merged *_rank.json files combine into master_flat_rank.json which should be renamed to a name that indicates that this is the final data file for elastic search like ArtOntology.

**What effects does your proposed solution have**
Better understandability of the ETL process 

**Additional context**
To view the dependencies see the openartbrowserETLDataFlowBPMN.png in the nextcloud folder documents/implementation

**Comment by JaGennis** [comment]
I suggest to rename master_flat_rank.json to art_ontology_ranked.json. This would on the one hand respect the naming conventions discussed in issue 40 as well as make clear that data is ranked.

**Comment by JaGennis** [comment]
I think we should rename "depicts" / "objects" to "motifs" so it is consistent with the webpage subjects.

**Comment by BernhardHumm** [comment]
Very good!

 

           Bernhard Humm

 

 

 

Von: JaGennis [mailto:notifications@github.com] 
Gesendet: Montag, 11. November 2019 21:12
An: hochschule-darmstadt/openartbrowser <openartbrowser@noreply.github.com>
Cc: Subscribed <subscribed@noreply.github.com>
Betreff: Re: [hochschule-darmstadt/openartbrowser] Name refactoring for generated ETL files (#21)

 

I think we should rename "depicts" / "objects" to "motifs" so it is consistent with the webpage subjects.
