### ISSUE TITLE
What about a realtime SPARQL interface

### ISSUE THREAD

**Issue by waldenn** [hochschule-darmstadt/openartbrowser#210]
**Is your feature request related to a problem? Please describe.**

Not a problem, but I feel a more "live" view on the Wikidata Art works might be very interesting as an alternative approach than copying the data onto the server. Eg. if I search for "Escher" I find nothing.

Has this been researched and/or considered? I am not sure how performant this would be though, but personally I would like this web app more if it meant having a live and thus more complete view of the Art works in Wikidata, even if things were a little bit slower.

For increasing performance, a pre-build browser-based local JSON cache (loaded into IndexedDB) could perhaps serve as the art ontology, while the images are still fetched from a remote server.

**Why do you want this feature? What goals should be achieved**

It would avoid a lot of data management / storage and  allow for faster feature development IMHO.

**Describe the solution you'd like**

Use a SPARQL-based query-system with the created Art + Artist ontology (in JSON) to fetch data needed from the browser. Have a script to keep the ontology up-to-date.

See also: [WADE](https://www.wikidata.org/wiki/Wikidata:WikiProject_Wiki_Art_Depiction_Explorer)

The WADE app has other issues, from what I see. Still hoping someone will crack this! :-)

**Additional context**

PS: The interface is so far is very nice! Though I would prefer infinite + vertical scrolling for the art works, and also a fixed sidebar for navigation (or a somewhat more compact layout).

Thanks!

**Comment by BernhardHumm** [comment]
No, this is not feasible.

Please close this issue

 

 

           Bernhard Humm

 

------------------------------------

 

 

Von: waldenn [mailto:notifications@github.com] 
Gesendet: Dienstag, 24. Dezember 2019 00:15
An: hochschule-darmstadt/openartbrowser <openartbrowser@noreply.github.com>
Cc: Subscribed <subscribed@noreply.github.com>
Betreff: [hochschule-darmstadt/openartbrowser] What about a realtime SPARQL interface (#210)

 

Is your feature request related to a problem? Please describe.

Not a problem, but I feel a more "live" view on the Wikidata Art works might be very interesting as an alternative approach than storing the data locally. Eg. if I search for "Escher" I find nothing.

Has this been researched and/or considered? I am not sure how performant this would be though, but personally I would like this web app more if it meant having a live and thus more complete view of the Art works in Wikidata, even if things were a little bit slower.

Why do you want this feature? What goals should be achieved

It would avoid a lot of data management / storage and allow for faster feature development IMHO.

Describe the solution you'd like

Use a SPARQL-based query-system with the created Art + Artist ontology (in JSON) to fetch data needed from the browser. Have an easy script to keep the ontologies up-to-date.

Additional context

PS: The interface is so far is very nice! Though I would prefer infinite + vertical scrolling for the art works, and also a fixed sidebar for navigation or a somewhat more predictable layout. The hover-animation is also a bit distracting IMHO.

Thank!
