### ISSUE TITLE
Label Information Overlapping 

### ISSUE THREAD

**Issue by xcaverxiii** [hochschule-darmstadt/openartbrowser#211]
UI bug 
![image](https://user-images.githubusercontent.com/25961416/70705273-0aea6780-1cd4-11ea-8993-2777bbbbecf5.png)

The problems comes by the unknown length of the labels for the different languages.

Maybe a table could solve this issue, but then the responsiveness would be risked.
Alternative the label field could be much wider, but this could look bad in some situations.

**Comment by mxxbe** [comment]
For some cases this can be solved by adapting the column width of `label` and `value` in the `information.component.html` - however it would not be guaranteed that this solves it for each case, and it looks a little strange in the english version for example (way too much space between the label and its value).

Other options are the HTML `fieldset` element (which is usually used for forms though.. ) and the css property `width: max-content` - both approaches didn't work with our current components though, so we might have to refactor them again, unless anyone else has a suggestion?

**Comment by stkeogie** [comment]
issue is duplicated. #312
