### ISSUE TITLE
Description fallback language is still english

### ISSUE THREAD

**Issue by tilomi** [hochschule-darmstadt/openartbrowser#212]
The default fallback for abstracts is still english i think this isn't correct.
Examples:
https://cai-artbrowserstaging.fbi.h-da.de/de/motif/Q6497468
https://www.wikidata.org/wiki/Q6497468

https://cai-artbrowserstaging.fbi.h-da.de/de/genre/Q1047337
https://www.wikidata.org/wiki/Q1047337

The source of the problem is the language split, i checked the json files

Edit: The problem were the descriptions not the abstracts as i thought first

**Comment by jschurse** [comment]
To clarify this issue: this is a problem with the description not the abstract, right?
As the abstract in the response for your first example is empty: 
https://cai-artbrowserstaging.fbi.h-da.de/api/de/_search?q=id:Q6497468

So the problem would be here:
https://github.com/hochschule-darmstadt/openartbrowser/blob/staging/scripts/Wikidata%20crawler/ArtOntologyCrawler.py#L233
https://github.com/hochschule-darmstadt/openartbrowser/blob/staging/scripts/Wikidata%20crawler/ArtOntologyCrawler.py#L327
where the english value of the description field is being added as the default case in the exception that a language specific field isn't being found.

**Comment by tilomi** [comment]
Ok i didn't check the description because i thought only abstracts were shown. This part should be done in the language split, i don't know why it is in the crawler it must've been overlooked when merging the multilanguage feature. I checked the frontend code for this there the abstract or description is picked https://github.com/hochschule-darmstadt/openartbrowser/blob/staging/app/src/app/shared/components/badge/badge.component.ts#L26 . I encountered unfortunatly another bug there i'll add a issue for this. I'll fix the crawler part on this one.

**Comment by tilomi** [comment]
#217

**Comment by tilomi** [comment]
I also checked the abstracts again in the files they seem to work correctly. It is only the description part.

**Comment by tilomi** [comment]
We have to check the split language script again, because of this error, it could be the case that the script doesn't work as intended for the blank filling when the fallbacks in the crawler script are removed

**Comment by tilomi** [comment]
#218 I tested the split languages script it works correctly. The part in the crawler was just redundant and overlooked i think
