### ISSUE TITLE
Tooltip doesn't work when abstract and description is available

### ISSUE THREAD

**Issue by tilomi** [hochschule-darmstadt/openartbrowser#217]
The tooltip picks the abstract or the description but the implementation doesn't seem to work in cases where both is available.
Example:
The motive beggar has description and abstract:
https://cai-artbrowserstaging.fbi.h-da.de/api/de/_search?q=id:Q273283

When i hover over the beggar Tag only "[...]" is shown:
https://cai-artbrowserstaging.fbi.h-da.de/de/artwork/Q58551663

**Comment by jschurse** [comment]
has been fixed
