### ISSUE TITLE
Check for possible performance improvements in the ETL process

### ISSUE THREAD

**Issue by tilomi** [hochschule-darmstadt/openartbrowser#22]
**Is your feature request related to a problem? Please describe.**
I tested the current ETL process. It took about 47 hours to generate the files necessary to import to the elastic search server. The data size is not that big to take this long to crawl, so i think there could be ways to optimize this process.

**Why do you want this feature? What goals should be achieved**
Faster ETL process. Especially first part where .csv-files are generated from wikidata pages

**Describe the solution you'd like**
I'd like to improve the query so that we get all results after one query instead of iterating through all paintings one by one (which is one select times 100.000 foreach painting site). If this is not possible multithreading could be a solution but im not sure how hard it is to implement with the pywikibot framework. Maybe pywikibot offers such a solution, i haven't found any parallel processing solution within pywikibot at the moment.

**Describe acceptance criteria**
The ETL process is a lot faster. It should be at least less than 5 hours.

**Describe alternatives you've considered**
If no direct sparql query or multithreading works, i don't have an idea at the moment

**What effects does your proposed solution have**
If the etl process is faster, new features like multilanguage, wikipedia abstract import and videos could be tested faster.

**Comment by tilomi** [comment]
I first tried out a query for the extract_artworks function that returns directly all wanted fields. Unfortunately the query time is limited to 60 seconds which is not enough for all paintings (the paintings result in the biggest csv-file) For more information see: [Wikidata Query limits](https://www.mediawiki.org/wiki/Wikidata_Query_Service/User_Manual#Query_limits). I will try ask for a longer query time to try out if this could fix the problem, but i don't know how long this request will take. For a short-term solution i would suggest multi-threading because there can be five parallel site loads per IP address (see Query limits). I also looked at the database dumps which can be found here [Wikidata Database dumps](https://dumps.wikimedia.org/wikidatawiki/entities/) the current dump size is around ~50 Gb. They could be queried with an additional program that has to be installed on the server but i think downloading 50 Gb to extract around 100 Mb is an ugly workaround.

- [Working query with all fields as required](https://query.wikidata.org/#SELECT%0A%3Fartwork%0A%28CONCAT%28%27%5B%27%2C%20GROUP_CONCAT%28DISTINCT%20%3Fclass%3BSEPARATOR%3D%27%2C%20%27%29%2C%20%27%5D%27%29%20as%20%3Fclasses%29%0A%3FartworkLabel%0A%3FartworkDescription%0A%3Fimage%0A%28CONCAT%28%27%5B%27%2CGROUP_CONCAT%28DISTINCT%20%3Fcreator%3BSEPARATOR%3D%27%2C%20%27%29%2C%20%27%5D%27%29%20as%20%3Fcreators%29%0A%28CONCAT%28%27%5B%27%2CGROUP_CONCAT%28DISTINCT%20%3Flocation%3BSEPARATOR%3D%27%2C%20%27%29%2C%20%27%5D%27%29%20as%20%3Flocations%29%0A%28CONCAT%28%27%5B%27%2CGROUP_CONCAT%28DISTINCT%20%3Fgenre%3BSEPARATOR%3D%27%2C%20%27%29%2C%20%27%5D%27%29%20as%20%3Fgenres%29%0A%28CONCAT%28%27%5B%27%2CGROUP_CONCAT%28DISTINCT%20%3Fmovement%3BSEPARATOR%3D%27%2C%20%27%29%2C%20%27%5D%27%29%20as%20%3Fmovements%29%0A%28YEAR%28xsd%3AdateTime%28%3Finception%29%29%20AS%20%3FinceptionYear%29%0A%28CONCAT%28%27%5B%27%2CGROUP_CONCAT%28DISTINCT%20%3Fmaterial%3BSEPARATOR%3D%27%2C%20%27%29%2C%20%27%5D%27%29%20as%20%3Fmaterials%29%0A%28CONCAT%28%27%5B%27%2CGROUP_CONCAT%28DISTINCT%20%3Fdepicts%3BSEPARATOR%3D%27%2C%20%27%29%2C%20%27%5D%27%29%20as%20%3Fdepictions%29%0A%3FcountryLabel%20%0A%3Fheight%20%0A%3Fwidth%20%0AWHERE%20%7B%0A%20%20SERVICE%20wikibase%3Alabel%20%7B%20bd%3AserviceParam%20wikibase%3Alanguage%20%22en%22%20.%20%7D%0A%20%20%3Fclass%20%28wdt%3AP279%2a%29%20wd%3AQ3305213%20.%0A%20%20%3Fartwork%20wdt%3AP31%20%3Fclass%20%3B%0A%20%20%20%20wdt%3AP170%20%3Fcreator%20%3B%0A%20%20%20%20wdt%3AP18%20%3Fimage%20.%0A%20%20%3Fartwork%20%20wdt%3AP276%20%3Flocation%20.%20%0A%20%20%3Fartwork%20wdt%3AP136%20%3Fgenre%20.%20%0A%20%20%3Fartwork%20wdt%3AP135%20%3Fmovement%20.%20%0A%20%20%3Fartwork%20wdt%3AP571%20%3Finception%20.%20%0A%20%20%3Fartwork%20wdt%3AP186%20%3Fmaterial%20.%0A%20%20%3Fartwork%20wdt%3AP180%20%3Fdepicts%20.%0A%20%20%3Fartwork%20wdt%3AP17%20%3Fcountry%20.%0A%20%20%3Fartwork%20wdt%3AP2048%20%3Fheight%20.%0A%20%20%3Fartwork%20wdt%3AP2049%20%3Fwidth%20.%0A%7D%20GROUP%20BY%20%3Fartwork%20%3FartworkLabel%20%3FartworkDescription%20%3Fimage%20%3Finception%20%3FcountryLabel%20%3Fheight%20%3Fwidth)

- [Query with optional fields (as programmed in the script) which timouts](https://query.wikidata.org/#SELECT%0A%3Fartwork%0A%28CONCAT%28%27%5B%27%2C%20GROUP_CONCAT%28DISTINCT%20%3Fclass%3BSEPARATOR%3D%27%2C%20%27%29%2C%20%27%5D%27%29%20as%20%3Fclasses%29%0A%3FartworkLabel%0A%3FartworkDescription%0A%3Fimage%0A%28CONCAT%28%27%5B%27%2CGROUP_CONCAT%28DISTINCT%20%3Fcreator%3BSEPARATOR%3D%27%2C%20%27%29%2C%20%27%5D%27%29%20as%20%3Fcreators%29%0A%28CONCAT%28%27%5B%27%2CGROUP_CONCAT%28DISTINCT%20%3Flocation%3BSEPARATOR%3D%27%2C%20%27%29%2C%20%27%5D%27%29%20as%20%3Flocations%29%0A%28CONCAT%28%27%5B%27%2CGROUP_CONCAT%28DISTINCT%20%3Fgenre%3BSEPARATOR%3D%27%2C%20%27%29%2C%20%27%5D%27%29%20as%20%3Fgenres%29%0A%28CONCAT%28%27%5B%27%2CGROUP_CONCAT%28DISTINCT%20%3Fmovement%3BSEPARATOR%3D%27%2C%20%27%29%2C%20%27%5D%27%29%20as%20%3Fmovements%29%0A%28YEAR%28xsd%3AdateTime%28%3Finception%29%29%20AS%20%3FinceptionYear%29%0A%28CONCAT%28%27%5B%27%2CGROUP_CONCAT%28DISTINCT%20%3Fmaterial%3BSEPARATOR%3D%27%2C%20%27%29%2C%20%27%5D%27%29%20as%20%3Fmaterials%29%0A%28CONCAT%28%27%5B%27%2CGROUP_CONCAT%28DISTINCT%20%3Fdepicts%3BSEPARATOR%3D%27%2C%20%27%29%2C%20%27%5D%27%29%20as%20%3Fdepictions%29%0A%3FcountryLabel%20%0A%3Fheight%20%0A%3Fwidth%20%0AWHERE%20%7B%0A%20%20SERVICE%20wikibase%3Alabel%20%7B%20bd%3AserviceParam%20wikibase%3Alanguage%20%22en%22%20.%20%7D%0A%20%20%3Fclass%20%28wdt%3AP279%2a%29%20wd%3AQ3305213%20.%0A%20%20%3Fartwork%20wdt%3AP31%20%3Fclass%20%3B%0A%20%20%20%20wdt%3AP170%20%3Fcreator%20%3B%0A%20%20%20%20wdt%3AP18%20%3Fimage%20.%0A%20%20OPTIONAL%20%7B%20%3Fartwork%20%20wdt%3AP276%20%3Flocation%20.%20%7D%0A%20%20OPTIONAL%20%7B%20%3Fartwork%20wdt%3AP136%20%3Fgenre%20.%20%7D%0A%20%20OPTIONAL%20%7B%20%3Fartwork%20wdt%3AP135%20%3Fmovement%20.%20%7D%0A%20%20OPTIONAL%20%7B%20%3Fartwork%20wdt%3AP571%20%3Finception%20.%20%7D%0A%20%20OPTIONAL%20%7B%20%3Fartwork%20wdt%3AP186%20%3Fmaterial%20.%20%7D%0A%20%20OPTIONAL%20%7B%20%3Fartwork%20wdt%3AP180%20%3Fdepicts%20.%20%7D%0A%20%20OPTIONAL%20%7B%20%3Fartwork%20wdt%3AP17%20%3Fcountry%20.%20%7D%0A%20%20OPTIONAL%20%7B%20%3Fartwork%20wdt%3AP2048%20%3Fheight%20.%20%7D%0A%20%20OPTIONAL%20%7B%20%3Fartwork%20wdt%3AP2049%20%3Fwidth%20.%20%7D%0A%7D%20GROUP%20BY%20%3Fartwork%20%3FartworkLabel%20%3FartworkDescription%20%3Fimage%20%3Finception%20%3FcountryLabel%20%3Fheight%20%3Fwidth)

**Comment by tilomi** [comment]
Another reason for the bad performance could be the many "try except"-blocks https://stackoverflow.com/questions/2522005/cost-of-exception-handlers-in-python . They should be substituted.

**Comment by BernhardHumm** [comment]
Auf keinen Fall try-catch Blocks ersetzen!

 

Die Erfahrung zeigt, dass es hunderte verschiedener Ausnahmen gibt, die sie nicht alle aufzählen können.  Die Leute können halt was auch immer in Wikidata einpflegen. 

Ich hatte zunächst versucht, eine Ausnahme nach der anderen abzuhandeln und bin dann zu der robusten Lösung übergegangen.

 

 

Viele Grüße

           Bernhard Humm

 

------------------------------------

Prof. Dr. Bernhard Humm

Geschäftsführender Direktor, Institut für angewandte Informatik Darmstadt (aiDa)

Vorsitzender Promotionsausschuss, Promotionszentrum Angewandte Informatik

h_da Hochschule Darmstadt - University of Applied Sciences, fbi Fachbereich Informatik 

Schöfferstr. 8b, D-64295 Darmstadt

Tel: +49 6151 16 38494, Fax: +49 6151 16 38935, Home Office: +49 6031 6714726

 <mailto:bernhard.humm@h-da.de> bernhard.humm@h-da.de, https://fbi.h-da.de/personen/personenseiten/bernhard-humm/

 

 

Von: Tilo Michel [mailto:notifications@github.com] 
Gesendet: Sonntag, 3. November 2019 15:57
An: hochschule-darmstadt/openartbrowser <openartbrowser@noreply.github.com>
Cc: Subscribed <subscribed@noreply.github.com>
Betreff: Re: [hochschule-darmstadt/openartbrowser] Check for possible performance improvements in the ETL process (#22)

 

Another reason for the bad performance could be the many "try except"-blocks https://stackoverflow.com/questions/2522005/cost-of-exception-handlers-in-python . They should be substituted.

**Comment by BernhardHumm** [comment]
Hallo Herr Michel,

 

wie schon gesagt: investieren Sie nicht zu viel Zeit in die Performance-Optimierung. 

Da gibt es wichtigere Projektaufgaben.

 

 

Viele Grüße

           Bernhard Humm

 

------------------------------------

Prof. Dr. Bernhard Humm

Geschäftsführender Direktor, Institut für angewandte Informatik Darmstadt (aiDa)

Vorsitzender Promotionsausschuss, Promotionszentrum Angewandte Informatik

h_da Hochschule Darmstadt - University of Applied Sciences, fbi Fachbereich Informatik 

Schöfferstr. 8b, D-64295 Darmstadt

Tel: +49 6151 16 38494, Fax: +49 6151 16 38935, Home Office: +49 6031 6714726

 <mailto:bernhard.humm@h-da.de> bernhard.humm@h-da.de, https://fbi.h-da.de/personen/personenseiten/bernhard-humm/

 

 

Von: Tilo Michel [mailto:notifications@github.com] 
Gesendet: Freitag, 1. November 2019 21:41
An: hochschule-darmstadt/openartbrowser <openartbrowser@noreply.github.com>
Cc: Subscribed <subscribed@noreply.github.com>
Betreff: Re: [hochschule-darmstadt/openartbrowser] Check for possible performance improvements in the ETL process (#22)

 

I first tried out a query for the extract_artworks function that returns directly all wanted fields. Unfortunately the query time is limited to 60 seconds which is not enough for all paintings (the paintings result in the biggest csv-file) For more information see: Wikidata Query limits <https://www.mediawiki.org/wiki/Wikidata_Query_Service/User_Manual#Query_limits> . I will try ask for a longer query time to try out if this could fix the problem, but i don't know how long this request will take. For a short-term solution i would suggest multi-threading because there can be five parallel site loads per IP address (see Query limits). I also looked at the database dumps which can be found here Wikidata Database dumps <https://dumps.wikimedia.org/wikidatawiki/entities/>  the current dump size is around ~50 Gb. They could be queried with an additional program that has to be installed on the server but i think downloading 50 Gb to extract around 100 Mb is an ugly workaround.

*        Working query with all fields as required

*        Query with optional fields (as programmed in the script) which timouts

**Comment by tilomi** [comment]
I wrote a ticket on wikimedia's ticket system phabricator.wikimedia.org . I got some answers but they are alternatives. One contributor said it could be the configuration but i checked this and had no improvments. Ticket link: https://phabricator.wikimedia.org/T238471
