### ISSUE TITLE
More is displayed but there is no additional information

### ISSUE THREAD

**Issue by tilomi** [hochschule-darmstadt/openartbrowser#220]
Example:
https://cai-artbrowserstaging.fbi.h-da.de/de/movement/Q1404472

Endpoint URL:
https://cai-artbrowserstaging.fbi.h-da.de/api/de/_search?q=id:Q1404472

I don't know whether the description should be displayed on movements but the video isn't displayed at all

**Comment by jschurse** [comment]
Fixed it.
