### ISSUE TITLE
JS Error when navigating to any entity page

### ISSUE THREAD

**Issue by mxxbe** [hochschule-darmstadt/openartbrowser#224]
## Steps to reproduce:

- Open an Artist page (e.g. Leonardo Da Vinci) and the developer console (F12)
- Then click any of his artworks

## Behavior:

- One or multiple JavaScript errors appear in the console.

![image](https://user-images.githubusercontent.com/22763390/72091284-17cc9c00-3310-11ea-88ef-f3b932109ffc.png)

## Expected Behavior: 

- no errors :)  

## Additional Info

- I am refering to the version that was available on the [staging url](https://cai-artbrowserstaging.fbi.h-da.de/) on Jan 9th 2020 so I guess the commit that introduced it could be [this one](https://github.com/hochschule-darmstadt/openartbrowser/commit/6a2035c0e294f262d4fc150d7f65e33d2e27887e).

**Comment by jschurse** [comment]
Thank you for this report!
The error has been fixed.
