### ISSUE TITLE
Display tooltip on badges under "Related Artworks"

### ISSUE THREAD

**Issue by jschurse** [hochschule-darmstadt/openartbrowser#235]
**Is your feature request related to a problem? Please describe.**
While hovering over a badge a tooltip with additional information is being shown.
![image](https://user-images.githubusercontent.com/12964877/72351269-57183580-36e0-11ea-8633-37cdef4cdfe9.png)

Hovering over the badges under "Related Artworks" does not yield such a result.

**Why do you want this feature? What goals should be achieved**
Consistency in UI/UX

**Describe the solution you'd like**
The same tooltips should be displayed while hovering these badges

**Additional context**
![image](https://user-images.githubusercontent.com/12964877/72351146-0f91a980-36e0-11ea-995b-acb9ecf4f972.png)

**Comment by mxxbe** [comment]
see #243
