### ISSUE TITLE
Increase margins on entity pages (For discussion)

### ISSUE THREAD

**Issue by lbucas** [hochschule-darmstadt/openartbrowser#254]
**Is your feature request related to a problem? Please describe.**
The entity pages look a bit overloaded when a lot of information is available. 

**Why do you want this feature? What goals should be achieved**
Improve the spacing to make the page more readable.

**Describe the solution you'd like**
Increased margins between the rows.

**Describe acceptance criteria**
No bugs and better readabilty.

**Describe alternatives you've considered**
/

**What effects does your proposed solution have**
Only design changes.

**Additional context**
![image](https://user-images.githubusercontent.com/32192444/72516192-8dc18d80-3851-11ea-9e36-eea48e3c2c39.png)

**Comment by EeveesEyes** [comment]
After a discussion this does not seem to be an issue.
