### ISSUE TITLE
Iconclass throws 503 and CORS errors

### ISSUE THREAD

**Issue by mauamy** [hochschule-darmstadt/openartbrowser#259]
**Issue description**
The artwork **Q9048912** throws a 503 and a CORS error on [staging](https://cai-artbrowserstaging.fbi.h-da.de/en/artwork/Q9048912) when trying to fetch the iconclass data.
This might be the case for other resources as well.

**Steps to reproduce the issue**

1.  Go to the [artwork on the staging server](https://cai-artbrowserstaging.fbi.h-da.de/en/artwork/Q9048912)
2. Open the developer console
3. Console outpout:
```
GET https://openartbrowser.org/api/iconclass/11R6.json 503 (Service Temporarily Unavailable)

Access to XMLHttpRequest at 'https://openartbrowser.org/api/iconclass/11R6.json' from origin 'https://cai-artbrowserstaging.fbi.h-da.de' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.

ERROR Error: Uncaught (in promise): e: {"headers":{"normalizedNames":{},"lazyUpdate":null,"headers":{}},"status":0,"statusText":"Unknown Error","url":"https://openartbrowser.org/api/iconclass/11R6.json","ok":false,"name":"HttpErrorResponse","message":"Http failure response for https://openartbrowser.org/api/iconclass/11R6.json: 0 Unknown Error","error":{"isTrusted":true}}
...
```

**What's the expected result?**
The request to the iconclass api should be successful.

**What's the actual result?**
The request throws HTTP 503 and CORS Errors.

**Additional details / screenshot**

![Screenshot from 2020-01-16 12-38-54](https://user-images.githubusercontent.com/28662686/72522115-2d384d80-385d-11ea-81db-18376c6c652d.png)

**Comment by mxxbe** [comment]
It seems like this was a temporary server problem, as it only occured on that day as far as I observed it over the last few days.
