### ISSUE TITLE
Repository "cleanup" and adjust readme's

### ISSUE THREAD

**Issue by tilomi** [hochschule-darmstadt/openartbrowser#260]
**Is your feature request related to a problem? Please describe.**
Some files in the repository are not used anymore like ArtOntology.zip which is an old data extraction or documents which contains some files of the nextcloud. Also the README.md on the "Frontpage" of the repository is not up-to-date.

**Why do you want this feature? What goals should be achieved**
Only important files should be in the repository.

**Describe the solution you'd like**
Removed all old files, READMEs adjusted.

**Describe acceptance criteria**
See above.

**Describe alternatives you've considered**
none

**What effects does your proposed solution have**
Better Maintainability.

**Comment by lbucas** [comment]
I think somebody proposed a new folder structure for the Angular app in a presentation (@xcaverxiii ?). We could also consider doing this before the end of the semester.

**Comment by xcaverxiii** [comment]
> I think somebody proposed a new folder structure for the Angular app in a presentation (@xcaverxiii ?). We could also consider doing this before the end of the semester.

It seems that this is the typical angular code structure. Split in core and shared components and pages. All in core will be used in every page. Thinks in shared can but must not used in a page.
