### ISSUE TITLE
Display a fallback view when the search does not yield results

### ISSUE THREAD

**Issue by mxxbe** [hochschule-darmstadt/openartbrowser#278]
**Is your feature request related to a problem? Please describe.**
When a user enters something in the search bar that can not be found in the es-index (see example) the search bar does not display anything to make him aware that his search can not yield any results.

![image](https://user-images.githubusercontent.com/22763390/73064000-7a8d6e00-3ea0-11ea-80c8-791348c5eba7.png)

**Why do you want this feature? What goals should be achieved**
For a better user experience we should offer a fallback view that tells the user that his search term can not be found. 
Additionally some alternative links could be displayed to give the user some different entry-point into the usual flow of exploration.

**Describe acceptance criteria**
Inserting a search term that does not yield results will cause the search bar to display some fallback UI with a message like "Unfortunately this search did not yield any results" (a bit more creative maybe).
The solution can be extended in the future ("did you mean..." / links to various topics to get the user exploring anyway)

**Describe alternatives you've considered**
We could also integrate a fuzzy search (example of a js implementation: https://fusejs.io/) that could offer alternative search terms (like google's "did you mean..." feature)

**What effects does your proposed solution have**
Better user experience, a more professional appearance / functionality of the search bar.

**Comment by BernhardHumm** [comment]
When the user enters a text and does not select an autosuggested term, then a full-text search is performed. 

This is the desired behavior. 

-> close this issue

 

 

           Bernhard Humm

 

------------------------------------

 

 

Von: Maximilian Belling [mailto:notifications@github.com] 
Gesendet: Freitag, 24. Januar 2020 12:07
An: hochschule-darmstadt/openartbrowser <openartbrowser@noreply.github.com>
Cc: Subscribed <subscribed@noreply.github.com>
Betreff: [hochschule-darmstadt/openartbrowser] Display a fallback view when the search does not yield results (#278)

 

Is your feature request related to a problem? Please describe.
When a user enters something in the search bar that can not be found in the es-index (see example) the search bar does not display anything to make him aware that his search can not yield any results.

 <https://user-images.githubusercontent.com/22763390/73064000-7a8d6e00-3ea0-11ea-80c8-791348c5eba7.png> 

Why do you want this feature? What goals should be achieved
For a better user experience we should offer a fallback view that tells the user that his search term can not be found.
Additionally some alternative links could be displayed to give the user some different entry-point into the usual flow of exploration.

Describe acceptance criteria
Inserting a search term that does not yield results will cause the search bar to display some fallback UI with a message like "Unfortunately this search did not yield any results" (a bit more creative maybe).
The solution can be extended in the future ("did you mean..." / links to various topics to get the user exploring anyway)

Describe alternatives you've considered
We could also integrate a fuzzy search that could offer alternative search terms (like google's "did you mean..." feature)

What effects does your proposed solution have
Better user experience, a more professional appearance / functionality of the search bar.
