### ISSUE TITLE
Additional Movement Attributes

### ISSUE THREAD

**Issue by EeveesEyes** [hochschule-darmstadt/openartbrowser#288]
**Is your feature request related to a problem? Please describe.**
Currently a movement does not link to its super-/ submovements or artists. 

**Why do you want this feature? What goals should be achieved**
More information = profit for user

**Describe the solution you'd like**
The movement should have the following attributes:
- start (P580) & end time (P582)
- supermovements (part of relation with constraint instance of 'art style' or 'art movement'  ) transitive
- submovements (transitive closure of inverse supermovement condition - computed as semantic enrichment as part of the ETL process)
- country (P17)
- artists (inverse relationship from artist to movements - computed as semantic enrichment as part of the ETL process)

**Describe acceptance criteria**
- backends implements crawling of additional wikidata attributes
- implements aggregation of transitive closure (has to be executed in the ETL process after #89)
- display labels

**Comment by tilomi** [comment]
supermovements (part of relation with constraint instance of 'art style' or 'art movement' ) transitive missing
