### ISSUE TITLE
Additional artwork attributes

### ISSUE THREAD

**Issue by BernhardHumm** [hochschule-darmstadt/openartbrowser#292]
**Reason**
More important information; increases learning effect and fun in using openArtBrowser

**Solution**
The following Wikidata attributes shall be crawled:
main subject (P921) -> main_motif (Hauptmotiv) (HIGH PRIO)
significant event (P793) (MEDIUM PRIO)
exhibition history (P608) (MEDIUM PRIO)

main_motif shall be displayed in artwork page (above motifs). When clicking on main motif chip, a motif component is opened. 
In related artworks, main motif shall be added to the "motif" tab (and, hence, to the all tab)

Significant events and exhibition history (MEDIUM PRIO): 
first check data and provide and discuss concept before start of implementation

**Alternatives**

**Effects**
Main motif gives information about the background of the artwork. 

**Acceptance criteria**

**Additional context**

**Comment by tilomi** [comment]
Should all main subjects be extracted or only the first? The Mona Lisa for example has two: https://www.wikidata.org/wiki/Q12418 . It could be the case that not all main subjects are known in the motifs file. Should unknown main subjects be ignored so that only motifs are shown there or should they be loaded too?

**Comment by BernhardHumm** [comment]
All main subjects shall be extracted.

All main subjects shall also be loaded in the motifs file.

 

 

------------------------------------

 

 

Von: Tilo Michel [mailto:notifications@github.com] 
Gesendet: Donnerstag, 23. April 2020 18:05
An: hochschule-darmstadt/openartbrowser <openartbrowser@noreply.github.com>
Cc: Humm, Bernhard, Prof. Dr. <bernhard.humm@h-da.de>; Author <author@noreply.github.com>
Betreff: Re: [hochschule-darmstadt/openartbrowser] Additional artwork attributes (#292)

 

Should all main subjects be extracted or only the first? The Mona Lisa for example has two: https://www.wikidata.org/wiki/Q12418 . It could be the case that not all main subjects are known in the motifs file. Should unknown main subjects be ignored so that only motifs are shown there or should they be loaded too?

**Comment by tilomi** [comment]
The extracting of the main subjects works. However i encountered another inconsistency in the data: The main subject is sometimes also in the motif collection and sometimes it isn't. There are now three options how to handle this issue:

1. Take the data from wikidata as is (Some main subjects are also in the motifs some aren't)
2. Always add the main subjects to the motifs (redundant)
3. Motifs are seperated from main subjects (This has to be implemented in the crawler then)

**Comment by BernhardHumm** [comment]
My opinion:

1.       We should take the Wikidata as is during crawling.

2.       On the artwork page, the redundant display of the main motif tag under motifs could be avoided (but doesn’t have to be – no harm)

3.       In the related artworks tab “motif”, the main motif shall be added to the motifs (and hence added to “all”)

 

 

------------------------------------

 

 

Von: Tilo Michel [mailto:notifications@github.com] 
Gesendet: Dienstag, 28. April 2020 11:50
An: hochschule-darmstadt/openartbrowser <openartbrowser@noreply.github.com>
Cc: Humm, Bernhard, Prof. Dr. <bernhard.humm@h-da.de>; Author <author@noreply.github.com>
Betreff: Re: [hochschule-darmstadt/openartbrowser] Additional artwork attributes (#292)

 

The extracting of the main subjects works. However i encountered another inconsistency in the data: The main subject is sometimes also in the motif collection and sometimes it isn't. There are now three options how to handle this issue:

1.	Take the data from wikidata as is (Some main subjects are also in the motifs some aren't)
2.	Always add the main subjects to the motifs (redundant)
3.	Motifs are seperated from main subjects (This has to be implemented in the crawler then)

**Comment by jschurse** [comment]
The high prio feature main_motif is implemented:
https://cai-artbrowserstaging.fbi.h-da.de/de/artwork/Q12418
and will be released with the next version.

The other fields 
significant event (P793) (MEDIUM PRIO)
exhibition history (P608) (MEDIUM PRIO)
are not yet implemented.

**Comment by BernhardHumm** [comment]
I don‘t have the impression that exhibitions are prominent enough to make it an entity. There are not too many exhibition entries, not too much interesting details about an exhibition so that browsing will not be fun (similar to the decisions not to make main subject or iconclass iconography separate entities since there are too few entries).

 

I suggest to implement this feature in a simple form:

Consider attributes significant event (P793) and exhibition history (P608)

For each entry try to get the following data: start time (year), label, end time (year, optional), description (optional).

Ignore all entries with missing start time and label.

Sort events according to start time.

Display as follows (example Mona Lisa):

 

Events: 1519                   acquisition (gain possession of a museum piece)

              1911-1913         theft of Mona Lisa

              1963                    Mona Lisa by Leonardo da Vinci (exhibition of the Mona Lisa at the National Gallery of Art, Washington D.C.)

              1963                    The Mona Lisa by Leonardo da Vinci (exhibition of the Mona Lisa at the Metropolitan Museum of Art, New York City)

              1974                    Mona Lisa Exhibition (exhibition of the Mona Lisa at Tokyo National Museum, Japan)

              

Rules for display:

If there are two different dates: write “<start year> - <end year>”, otherwise just “<start year>”

Display label and, if existing), description in parenthesis. 

If description of exhibition is missing, write “(exhibition)”

 

------------------------------------

 

Von: Maximilian Belling [mailto:notifications@github.com] 
Gesendet: Mittwoch, 10. Juni 2020 17:29
An: hochschule-darmstadt/openartbrowser <openartbrowser@noreply.github.com>
Cc: Humm, Bernhard, Prof. Dr. <bernhard.humm@h-da.de>; Author <author@noreply.github.com>
Betreff: Re: [hochschule-darmstadt/openartbrowser] Additional artwork attributes (#292)

 

Since the significant events attribute is very complex.
There are a lot of different types of significant events, which makes it hard to
a) crawl the data, and resolve all the references to labels
b) display all the different event types in a consistent way on the client

We (@tilomi <https://github.com/tilomi> , @jschurse <https://github.com/jschurse> , @DasDave42 <https://github.com/DasDave42> , me) came to the conclusion, that we would like to implement the exhibition history first.

Our current idea is:

*	creating a new Entity "ArtExhibition" or "Exhibition", extend the crawling process, to include the attribute and create entities of the new type in ES
*	introduce a new type of page in the client, that displays ArtExhibitions (for example like the Artist page), including some data about the Exhibition, and references to exhibited Artworks.
*	cross-reference the ArtExhibition page from the Artwork (and have the Artwork display all Exhibitions it was exhibited in - that we know of) with the small badges

**Comment by BernhardHumm** [comment]
Slight modification of rules for display:

 

For significant events, display label only (!).

For exhibitions, display label and, if existing, description in parenthesis, otherwise “(exhibition)”

 

 

------------------------------------

 

 

Von: Humm, Bernhard, Prof. Dr. 
Gesendet: Donnerstag, 11. Juni 2020 13:45
An: 'hochschule-darmstadt/openartbrowser' <reply@reply.github.com>; hochschule-darmstadt/openartbrowser <openartbrowser@noreply.github.com>
Cc: Belling, Maximilian (Stud. FBI) <maximilian.belling@stud.h-da.de>; Schurse, Jenja (Stud. FBI) <jenja.schurse@stud.h-da.de>; Michel, Tilo Werner (Stud. FBI) <tilo.w.michel@stud.h-da.de>
Betreff: AW: [hochschule-darmstadt/openartbrowser] Additional artwork attributes (#292)

 

I don‘t have the impression that exhibitions are prominent enough to make it an entity. There are not too many exhibition entries, not too much interesting details about an exhibition so that browsing will not be fun (similar to the decisions not to make main subject or iconclass iconography separate entities since there are too few entries).

 

I suggest to implement this feature in a simple form:

Consider attributes significant event (P793) and exhibition history (P608)

For each entry try to get the following data: start time (year), label, end time (year, optional), description (optional).

Ignore all entries with missing start time and label.

Sort events according to start time.

Display as follows (example Mona Lisa):

 

Events: 1519                   acquisition (gain possession of a museum piece)

              1911-1913         theft of Mona Lisa

              1963                    Mona Lisa by Leonardo da Vinci (exhibition of the Mona Lisa at the National Gallery of Art, Washington D.C.)

              1963                    The Mona Lisa by Leonardo da Vinci (exhibition of the Mona Lisa at the Metropolitan Museum of Art, New York City)

              1974                    Mona Lisa Exhibition (exhibition of the Mona Lisa at Tokyo National Museum, Japan)

              

Rules for display:

If there are two different dates: write “<start year> - <end year>”, otherwise just “<start year>”

Display label and, if existing), description in parenthesis. 

If description of exhibition is missing, write “(exhibition)”

 

------------------------------------

 

Von: Maximilian Belling [mailto:notifications@github.com] 
Gesendet: Mittwoch, 10. Juni 2020 17:29
An: hochschule-darmstadt/openartbrowser <openartbrowser@noreply.github.com <mailto:openartbrowser@noreply.github.com> >
Cc: Humm, Bernhard, Prof. Dr. <bernhard.humm@h-da.de <mailto:bernhard.humm@h-da.de> >; Author <author@noreply.github.com <mailto:author@noreply.github.com> >
Betreff: Re: [hochschule-darmstadt/openartbrowser] Additional artwork attributes (#292)

 

Since the significant events attribute is very complex.
There are a lot of different types of significant events, which makes it hard to
a) crawl the data, and resolve all the references to labels
b) display all the different event types in a consistent way on the client

We (@tilomi <https://github.com/tilomi> , @jschurse <https://github.com/jschurse> , @DasDave42 <https://github.com/DasDave42> , me) came to the conclusion, that we would like to implement the exhibition history first.

Our current idea is:

*	creating a new Entity "ArtExhibition" or "Exhibition", extend the crawling process, to include the attribute and create entities of the new type in ES
*	introduce a new type of page in the client, that displays ArtExhibitions (for example like the Artist page), including some data about the Exhibition, and references to exhibited Artworks.
*	cross-reference the ArtExhibition page from the Artwork (and have the Artwork display all Exhibitions it was exhibited in - that we know of) with the small badges

**Comment by mxxbe** [comment]
closing this, since we created sub-issues #410 and #409 to separate the different requirements
