### ISSUE TITLE
Continuous scrolling of artworks

### ISSUE THREAD

**Issue by BernhardHumm** [hochschule-darmstadt/openartbrowser#294]
**Reason**
Currently, a maximum number of artworks (200) for a genre, movement, location, artist, material, motif is displayed. If more artworks are available, they cannot be displayed by scrolling in the carousel.

**Solution**
Implement continuous scrolling of artworks. When the last artworks out of 200 are displayed, then the next 201-400 artworks are loaded and displayed, and so on until all artworks are loaded. 

**Alternatives**

**Effects**
All artworks are displayed

**Acceptance criteria**

**Additional context**
related to #293 , #57

**Comment by EeveesEyes** [comment]
Solved by #460
