### ISSUE TITLE
Missing artwork height / width

### ISSUE THREAD

**Issue by BernhardHumm** [hochschule-darmstadt/openartbrowser#297]
**Reason**
For artwork without dimension data the display is: 
Dimension: x cm
Example: https://openartbrowser.org/en/artwork/Q3227834

**Solution**
If the dimension data is missing then no dimension entry shall be displayed at all.

**Alternatives**

**Effects**

**Acceptance criteria**

**Additional context**

**Comment by jschurse** [comment]
We also have the problem that some objects are two dimensional (width x height) like a painting on canvas or a drawing on paper. 
Others like skulptures are three dimensional (width x height x depth) so the [formatting expression in the template](https://github.com/hochschule-darmstadt/openartbrowser/blob/c37344a1ea4ccd2ff8404037d8e5b6e48047eaf2/app/src/app/pages/artwork/artwork.component.html#L54) is insufficient 

If the artbrowser should be extended in the future to display objects like antique coins or rings there comes another style of size formatting (diameter/radius)

I propose to implement some sort of sizeFormatter functionality which takes the Artwork Entity as parameter and returns the rendered dimensions based on the available data and the type of artwork.
