### ISSUE TITLE
Include unit of measurement for height / width

### ISSUE THREAD

**Issue by BernhardHumm** [hochschule-darmstadt/openartbrowser#298]

**Comment by BernhardHumm** [comment]
**Reason**
Currently, the height and width of an artwork is loaded from Wikidata but the unit of measurement (which is provided in Wikidata) is not loaded. Instead, cm is assumed. This may be wrong.

**Solution**
Add artwork attributes height_unit , width_unit and load from Wikidata.
Display units of measurement on artworks page, e.g, 
Dimension: 470 x 337cm
Dimension: 43 x 56 in
Dimension: 1.5m x 45 cm   [if units of measurements differ!]

**Alternatives**

**Effects**


**Acceptance criteria**


**Additional context**

**Comment by jschurse** [comment]
Here is an example for a wrong unit:
http://openartbrowser.org/en/artwork/Q16388663

**Comment by stkeogie** [comment]
Some artworks also contain a length- or a diameter attribute, I think we should add those attributes and load them from Wikidata.

Here are some examples:
https://www.wikidata.org/wiki/Q56397959
https://www.wikidata.org/wiki/Q17280208

**Comment by stkeogie** [comment]
Properties that need to be crawled:
diameter, length, height_unit, width_unit, length_unit, diameter_unit

**Comment by tilomi** [comment]
Resolved
