### ISSUE TITLE
Use https for eleastic search URL

### ISSUE THREAD

**Issue by waldenn** [hochschule-darmstadt/openartbrowser#3]
I tried to install this interesting project, but am having a "blocked content" issue with the http-URL used by the search API:

  https://github.com/hochschule-darmstadt/openartbrowser/blob/master/app/src/app/core/services/data.service.ts#L21

Could you please update this API to be on https?

Would also be great to better describe setting up your own an Elastic search service with the JSON data. There is [this file](https://github.com/hochschule-darmstadt/openartbrowser/blob/master/scripts/upload_to_elasticsearch/elastic.py), but a bit more help would be nice for those who have never used Elastic search.

I am interested in integrating this tool (self-hosted in an iframe) within the [Wikischool Explore](https://wikischool.org/explore/) tool, to allow for art work browsing from some subjects.

Thanks!

**Comment by BernhardHumm** [comment]
Thank you for your hints which we will consider for the next release.

You can use OpenArtBrowser online under  <http://openartbrowser.org/> http://openartbrowser.org

 

 

Best regards

           Bernhard 

 

-------------------------------------

Prof. Bernhard  G. Humm, Ph.D.

Managing Director, Institute for Applied Informatics, Darmstadt (aiDa); Ph.D. Coordinator

h_da Hochschule Darmstadt - University of Applied Sciences, Computer Science Department

Schöfferstr. 8b, 64295 Darmstadt, Germany

Phone: +49 6151 16 38494, Fax: +49 6151 16 38935, Home Office: +49 6031 6714726

bernhard.humm@h-da.de <mailto:bernhard.humm@h-da.de> ,  <https://fbi.h-da.de/personen/personenseiten/bernhard-humm/> https://fbi.h-da.de/personen/personenseiten/bernhard-humm/

 

Von: waldenn [mailto:notifications@github.com] 
Gesendet: Freitag, 6. September 2019 11:21
An: hochschule-darmstadt/openartbrowser <openartbrowser@noreply.github.com>
Cc: Subscribed <subscribed@noreply.github.com>
Betreff: [hochschule-darmstadt/openartbrowser] Use https for eleastic search URL (#3)

 

I tried to install this interesting project, but am having a "blocked content" issue with the http-URL used by the search API:

https://github.com/hochschule-darmstadt/openartbrowser/blob/master/app/src/app/core/services/data.service.ts#L21

Could you please update this API to be on https?

Would also be nice better describe setting up your own an Elastic search service with the data. There is this file <https://github.com/hochschule-darmstadt/openartbrowser/blob/master/app/src/app/core/services/data.service.ts#L21> , but a bit more help would be nice for those who have never used Elastic search.

Thanks!

**Comment by waldenn** [comment]
Thanks!

**Comment by jschurse** [comment]
Was fixed with #13
