### ISSUE TITLE
Overlapping labels for long translations

### ISSUE THREAD

**Issue by istthabel** [hochschule-darmstadt/openartbrowser#30]
**Is your feature request related to a problem? Please describe.**
Long labels overlap with their values at certain window widths (e.g. 1100px, see context below). This poses a problem with translated labels, that change their length depending on the language.

**Why do you want this feature? What goals should be achieved**
We want a dynamic solution for the place that is allocated for labels, so they do not overlap with their values.

**Describe the solution you'd like**
Information pairs (label, value) should be listed in tables of two columns.

**Describe acceptance criteria**
Labels do not overlap with values at any window width (e.g. 1100px)

**Describe alternatives you've considered**
Larger padding - would be static and look ugly for shorter translations.

**What effects does your proposed solution have**
Formatting of the label-value-pairs has to be coordinated with their translation.

**Additional context**
Issue #9 Add angular i18n functionality

>> It seems like the overlapping labels come from this styling directive
>> 
>> ```
>> .info[_ngcontent-lrl-c11] {
>>     margin-left: -2em;
>> }
>> ```
>
>Ohh yeah, but with a width from 1100px there is always some overlapping. And this problem will also occur if some other language has a very long word for an label.
>
>![image](https://user-images.githubusercontent.com/25961416/68142698-3e491200-ff30-11e9-8c0f-e533056510bd.png)
>
>One raw has always `col-md-3` for the label and `col-md-9` for the content. Maybe the label field must be wider, or that's the ideal case for a table, isn´t it?
>
_Originally posted by @xcaverxiii in https://github.com/hochschule-darmstadt/openartbrowser/issues/9#issuecomment-549461424_

**Comment by JamieArmstrongArndt** [comment]
Issue is done, approved and merged, therefore closed.
