### ISSUE TITLE
Infer movements of artist from movements of artworks

### ISSUE THREAD

**Issue by BernhardHumm** [hochschule-darmstadt/openartbrowser#302]
**Reason**
The movement information of artists is relatively poorly edited in Wikidata. 

**Solution**
Infer movements of artist from movements of artworks. All movements of artworks of an artists are added to his/her movements (use set - no duplicates).
Do this as semantic enrichment as part of the ETL process.
Check for dependencies to other semantic enrichment steps, e.g., collecting all artists belonging to a movement #288

**Alternatives**

**Effects**
More information for artist, more search results when searching for movement

**Acceptance criteria**

**Additional context**
related to #288

**Comment by tilomi** [comment]
This is already implemented in the frontend https://github.com/hochschule-darmstadt/openartbrowser/blob/master/app/src/app/pages/artist/artist.component.ts#L66 . I remember we decided to load it in the frontend because the artworks are loaded anyway in the artworks tab.
