### ISSUE TITLE
Display description of locations

### ISSUE THREAD

**Issue by BernhardHumm** [hochschule-darmstadt/openartbrowser#305]
**Reason**
The description attribute of locations seems to be meaningful but is currently not displayed on the location component

**Solution**
Display description like in the motif component

**Alternatives**

**Effects**
TODO: check whether description is meaningful for most cases. 

**Acceptance criteria**

**Additional context**

**Comment by EeveesEyes** [comment]
I actually think the motif-description seems some kind out of space. What do you think of something like this?
![tmp](https://user-images.githubusercontent.com/28682931/80706922-6e412e80-8ae9-11ea-80e0-8044d4d2905a.png)
Note that it is vertically aligned, slightly less highlighted and without big spacing under the label.

**Comment by BernhardHumm** [comment]
See #304

Abstract should be hidden in „More”

 

------------------------------------

 

 

Von: Adrian Kailus [mailto:notifications@github.com] 
Gesendet: Donnerstag, 30. April 2020 13:52
An: hochschule-darmstadt/openartbrowser <openartbrowser@noreply.github.com>
Cc: Humm, Bernhard, Prof. Dr. <bernhard.humm@h-da.de>; Author <author@noreply.github.com>
Betreff: Re: [hochschule-darmstadt/openartbrowser] Display description of locations (#305)

 

I actually think the motif-description seems some kind out of space. What do you think of something like this?
 <https://user-images.githubusercontent.com/28682931/80706922-6e412e80-8ae9-11ea-80e0-8044d4d2905a.png> 
Note that it is vertically aligned, slightly less highlighted and without big spacing under the label.
