### ISSUE TITLE
Timelines: start in the middle of the period

### ISSUE THREAD

**Issue by BernhardHumm** [hochschule-darmstadt/openartbrowser#308]
**Reason**
Currently, timelines (artist, movement) are initially at the beginning of the period when opening an artist / movement page. 
Often, the early works of an artist / movement are not typical.

**Solution**
Show the middle of the timeline when opening an artist / movement page

**Alternatives**

**Effects**
Typical artworks are displayed

**Acceptance criteria**

**Additional context**

**Comment by jschurse** [comment]
Has been implemented: https://cai-artbrowserstaging.fbi.h-da.de/de/artist/Q5598
Will be released with the next version.
