### ISSUE TITLE
Artist component: Overlapping labels

### ISSUE THREAD

**Issue by BernhardHumm** [hochschule-darmstadt/openartbrowser#312]
**Reason**
In the German artist page, the labels "Geboren" and "Gestorben" overlap the values.
Example: https://openartbrowser.org/de/artist/Q455133

**Solution**
Avoid overlapping.
Also check other components and other languages
Make sure that solution also works on other devices

**Alternatives**

**Effects**

**Acceptance criteria**

**Additional context**

**Comment by jschurse** [comment]
Fixed:
https://cai-artbrowserstaging.fbi.h-da.de/de/artist/Q455133

Will be released with the next version
