### ISSUE TITLE
Exported json meta data

### ISSUE THREAD

**Issue by paulsonnentag** [hochschule-darmstadt/openartbrowser#315]
Hi everyone,

I was looking for a publicly available dataset of artworks and stumbled upon your excellent project. I was wondering if you have the raw metadata about the artworks accessible somewhere as a JSON file or CSV. I've looked at the documentation and saw that it could take up to 6 days to run the import script. It would be great if I had some example data earlier for experimentation.

Thanks :)

**Comment by BernhardHumm** [comment]
Dear Paul,

 

send me an email address and then I can send you an RDF Turtle file (90MB) via WeTransfer.

 

 

Best regards

           Bernhard 

 

-------------------------------------

Prof. Bernhard  G. Humm, Ph.D.

Managing Director, Institute for Applied Informatics, Darmstadt (aiDa); Ph.D. Coordinator

h_da Hochschule Darmstadt - University of Applied Sciences, Computer Science Department

Schöfferstr. 8b, 64295 Darmstadt, Germany

Phone: +49 6151 16 38494, Fax: +49 6151 16 38935, Home Office: +49 6031 6714726

bernhard.humm@h-da.de <mailto:bernhard.humm@h-da.de> ,  <https://fbi.h-da.de/personen/personenseiten/bernhard-humm/> https://fbi.h-da.de/personen/personenseiten/bernhard-humm/

 

Von: Paul Sonnentag [mailto:notifications@github.com] 
Gesendet: Dienstag, 14. April 2020 10:31
An: hochschule-darmstadt/openartbrowser <openartbrowser@noreply.github.com>
Cc: Subscribed <subscribed@noreply.github.com>
Betreff: [hochschule-darmstadt/openartbrowser] Exported json meta data (#315)

 

Hi everyone,

I was looking for a publicly available dataset of artworks and stumbled upon your excellent project. I was wondering if you have the raw metadata about the artworks accessible somewhere as a JSON file or CSV. I've looked at the documentation and saw that it could take up to 6 days to run the import script. It would be great if I had some example data earlier for experimentation.

Thanks :)

**Comment by paulsonnentag** [comment]
Thanks for the quick reply. Can you send me the link to paul.sonnentag@googlemail.com?

**Comment by BernhardHumm** [comment]
Done

 

 

Best regards

           Bernhard 

 

-------------------------------------

Prof. Bernhard  G. Humm, Ph.D.

Managing Director, Institute for Applied Informatics, Darmstadt (aiDa); Ph.D. Coordinator

h_da Hochschule Darmstadt - University of Applied Sciences, Computer Science Department

Schöfferstr. 8b, 64295 Darmstadt, Germany

Phone: +49 6151 16 38494, Fax: +49 6151 16 38935, Home Office: +49 6031 6714726

bernhard.humm@h-da.de <mailto:bernhard.humm@h-da.de> ,  <https://fbi.h-da.de/personen/personenseiten/bernhard-humm/> https://fbi.h-da.de/personen/personenseiten/bernhard-humm/

 

Von: Paul Sonnentag [mailto:notifications@github.com] 
Gesendet: Dienstag, 14. April 2020 16:54
An: hochschule-darmstadt/openartbrowser <openartbrowser@noreply.github.com>
Cc: Humm, Bernhard, Prof. Dr. <bernhard.humm@h-da.de>; Comment <comment@noreply.github.com>
Betreff: Re: [hochschule-darmstadt/openartbrowser] Exported json meta data (#315)

 

Thanks for the quick reply. Can you send me the link to paul.sonnentag@googlemail.com <mailto:paul.sonnentag@googlemail.com> ?

**Comment by paulsonnentag** [comment]
Thank you very much!
