### ISSUE TITLE
Fix reverse proxy for /_count and /api

### ISSUE THREAD

**Issue by EeveesEyes** [hochschule-darmstadt/openartbrowser#321]
**Describe the bug**
/api/_count and /api/analytics paths are currently unavialable and have to be fixed

**To Reproduce**
Steps to reproduce the behavior for /api/analytics:
1. Go to eg. www.openartbrowser.org/api/analytics
2. Log into matomo
3. Site gets redirected to www.openartbrowser.org/en/

**Expected behavior**
There should be a way to get to the analytics page.

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Browser Vivaldi (Chromium based)
 - Version 3.0.1874.23 (Stable channel) (64-bit)

**Comment by jschurse** [comment]
The _count endpoint was never used and therefore never declared in the proxy conf.
I added the endpoints like we did for the search e.g:

- https://openartbrowser.org/api/de/_count
- https://openartbrowser.org/api/en/_count
- https://openartbrowser.org/api/fr/_count



The redirect problem with the analytics tools seems to be a bug when running matomo in a subdir:

- https://github.com/matomo-org/matomo/issues/13627
- https://forum.matomo.org/t/bug-proxy-redirect-to-root-after-login-success-instead-of-staying-within-assigned-sub-folder/19924/3

You can bypass this by calling the endpoint again after you login to access the admin panel.
