### ISSUE TITLE
Implement Dimension Sizeformatter for artwork page

### ISSUE THREAD

**Issue by stkeogie** [hochschule-darmstadt/openartbrowser#326]
Reason
Some objects are two dimensional (width x height) others like sculptures are three dimensional (width x height x depth). So the current Dimension-Format is insufficient.

Solution
This needs to be discussed. Note that #298 is directly linked to this.

Alternatives

Effects

Acceptance criteria

Additional context

_Originally posted by @jschurse in https://github.com/hochschule-darmstadt/openartbrowser/issues/297#issuecomment-621160986_

**Comment by EeveesEyes** [comment]
Please link associated issue

**Comment by jschurse** [comment]
@see https://github.com/hochschule-darmstadt/openartbrowser/issues/297

I think it would be good to refactor the current solution (https://github.com/hochschule-darmstadt/openartbrowser/pull/325) into it´s own component.
Currently we added [14 lines of decision based rendering logic](https://github.com/hochschule-darmstadt/openartbrowser/pull/325/files#diff-2a1eca21eadcc4cf8856015bf2b80bd0R54) to the artwork page and [approximately the same amount of lines](https://github.com/hochschule-darmstadt/openartbrowser/pull/325/files#diff-a13c5364d00994dfc65b316eb8fe471bR133) to the components logic.

I propse to abstract from this rendering logic in the artwork page for the benefit of seperation of concerns. 
The page should describe what content is shown and the layout (so for example semantically express that there will be artwork sizes rendered) but I don`t think the artwork page has the responsibility to decide how to render this information.


@EeveesEyes @mauamy @mxxbe @stkeogie any thoughts on this?

**Comment by stkeogie** [comment]
I also think it would be better to create a separate component because more dimensions and units will be added. That will increase the logic needed to determine which dimensions to represent.

**Comment by tilomi** [comment]
Are there any examples for sculptures which have all three dimensional values? Also please create an issue for the backend properties which have to be crawled from wikidata and assign it to me. At the moment there is only width and height see the Mona Lisa as example: https://openartbrowser.org/api/en/_search?q=id:Q12418 . The units are also missing, i think they're always set to cm.

**Comment by stkeogie** [comment]
Length-Parameter
https://www.wikidata.org/wiki/Q56397959
Diameter-Parameter:
https://www.wikidata.org/wiki/Q63854406

**Comment by stkeogie** [comment]
Sizeformatter has been merged into staging
