### ISSUE TITLE
Refactor Information Component and remove Hyperlink Component

### ISSUE THREAD

**Issue by jschurse** [hochschule-darmstadt/openartbrowser#340]
**Is your feature request related to a problem? Please describe.**
Currently we have two very similar components to render a label with the corresponding value. An Information Component to render plain Text and a hyperlink component to render an hyperlink.
[hyperlink-component](https://github.com/hochschule-darmstadt/openartbrowser/blob/staging/app/src/app/shared/components/hyperlink/hyperlink.component.html)
[information-component](https://github.com/hochschule-darmstadt/openartbrowser/blob/staging/app/src/app/shared/components/information/information.component.html)

**Why do you want this feature? What goals should be achieved**
To reduce code duplication and to ensure a high level of maintainability I propose to refactor the Information Component.

**Describe the solution you'd like**
The Information-Component should be refactored to accept an optional href attribute.
If this attribute is set the Information-Component should conditionally use an <a> tag to render the hyperlink.

**Additional context**
In the meeting last week I said, that it could be useful to have a custom Hyperlink-Component to use at other places where we need to work with hyperlinks and for example do link validation.
I looked up the places where we did this but we also refactored this functionality [into the video component](https://github.com/hochschule-darmstadt/openartbrowser/blob/staging/app/src/app/shared/components/video/video.component.ts). It currently seems to be the only place where we need to do additional logic before rendering the link so I don't see the need for a custom hyperlink component.

**Comment by mxxbe** [comment]
can be closed once #360 is merged
