### ISSUE TITLE
Distinguishing between Staging and Live System

### ISSUE THREAD

**Issue by jschurse** [hochschule-darmstadt/openartbrowser#36]
**Is your feature request related to a problem? Please describe.**
In order to ensure a smooth development and deploy process, features have to be integrated and tested before release.
For this we use a staging system which is a different (physical) system than our live system. 

**Why do you want this feature? What goals should be achieved**
The software has to make decisions based on it's environment. E.g. which Elasticsearch backend should be used.

**Describe the solution you'd like**
A solution would be to have an .env file in which environment variables like IS_TESTING or ELASTICSEARCH_URL could be configured.

**Describe acceptance criteria**
The software runs on both the staging and live system with the same code base and only different config files

**Describe alternatives you've considered**
For the serverURI which provides the location for our elasticsearch backend we could use a relative URL like `/api/_search` instead of the currently used absolute url `//openartbrowser.org/api/_search`
This would be acceptable for the staging and live system but not for the developers systems where no local elasticsearch is installed.

**What effects does your proposed solution have**
Another config file one needs to maintain.
This can be lessened if the software uses default fallbacks if no config / or only a partial config is being provided.

**Comment by jschurse** [comment]
> **Describe alternatives you've considered**
> For the serverURI which provides the location for our elasticsearch backend we could use a relative URL like `/api/_search` instead of the currently used absolute url `//openartbrowser.org/api/_search`
> This would be acceptable for the staging and live system but not for the developers systems where no local elasticsearch is installed.

This could be solved by using the proxy feature for local development:
https://github.com/angular/angular-cli/blob/master/docs/documentation/stories/proxy.md
So calls to localhost:4200/api would be redirected to openartbrowser.org/api
If a developer wants to use a different backend (like a local docker container) it can be mapped by editing the proxy.conf.json file

**Comment by mxxbe** [comment]
Can't we just provide something like `ES_BASE_URL` as an environment variable in order to solve this?

Locally, developers can then either chose the staging / live / docker-machine address / hostname - and for deployment we can configure each machine separately. 

Alternatively we can have a look at the proxy that you suggested, my point is basically if we can prevent an additional config file we should :)

**Comment by jschurse** [comment]
> my point is basically if we can prevent an additional config file we should :)

This was exactly my train of thought. 
If we set the `serverURI` variable to `/api/_search` we don't need to distinguishing between the staging, the live and the development system when using the `proxy.conf.json` in `ng serve` for local development.

Do you know of any other case for different configurations on these platforms?
If so we would need an .env file anyway, then we could just go with that.

**Comment by mxxbe** [comment]
Since we generally don't need an .env file right now (see #35), and I don't know of any other variables we want to make configurable right now, the proxy.conf solution looks promising 👍

**Comment by mxxbe** [comment]
Was merged, so I close the issue 😉
