### ISSUE TITLE
"more" tab unfolded when opening motif page

### ISSUE THREAD

**Issue by BernhardHumm** [hochschule-darmstadt/openartbrowser#394]
**Describe the bug**
When opening a page, the "more" tab should always initially be folded.
For motif pages this is not always the case.

**To Reproduce**
https://openartbrowser.org/de/motif/Q366134

**Expected behavior**

**Additional context**
Fix and check for other pages.

**Comment by EeveesEyes** [comment]
That's because we have very little information in the 'More' section and the page doesn't get expanded too much. If an abstract is <400 chars long, we only add 3 instead of 10 points to the _metaNumber_ which decides whether to show the abstract or not. I think this is a requirement from the start of the project.

**Comment by BernhardHumm** [comment]
The effect of the current implementation is that space is covered by text instead of images. Instead, the idea of openArtBrowser is to focus on image data.

It would be such a simple solution: on page opening, always fold the “more” tab; unfold only by user click.

 

 

------------------------------------

 

 

 

Von: Adrian Kailus [mailto:notifications@github.com] 
Gesendet: Dienstag, 16. Juni 2020 15:55
An: hochschule-darmstadt/openartbrowser <openartbrowser@noreply.github.com>
Cc: Humm, Bernhard, Prof. Dr. <bernhard.humm@h-da.de>; Author <author@noreply.github.com>
Betreff: Re: [hochschule-darmstadt/openartbrowser] "more" tab unfolded when opening motif page (#394)

 

That's because we have very little information in the 'More' section and the page doesn't get expanded too much. If an abstract is <400 chars long, we only add 3 instead of 10 points to the metaNumber which decides whether to show the abstract or not. I think this is a requirement from the start of the project.

**Comment by EeveesEyes** [comment]
Sure it would be easy but is this the new requirement? Because at the moment it seems like a feature that the more-section is displayed when it has a small amount of content. This applies not only to the motif-page but for all other entity-pages, too.
I personally think that clicking on 'more' and only getting one additional info like one sentence could be disappointing to the user.

**Comment by BernhardHumm** [comment]
OK, then leave it the way it is.

 

 

 

------------------------------------

 

Von: Adrian Kailus [mailto:notifications@github.com] 
Gesendet: Donnerstag, 18. Juni 2020 14:06
An: hochschule-darmstadt/openartbrowser <openartbrowser@noreply.github.com>
Cc: Humm, Bernhard, Prof. Dr. <bernhard.humm@h-da.de>; Author <author@noreply.github.com>
Betreff: Re: [hochschule-darmstadt/openartbrowser] "more" tab unfolded when opening motif page (#394)

 

Sure it would be easy but is this the new requirement? Because at the moment it seems like a feature that the more-section is displayed when it has a small amount of content. This applies not only to the motif-page but for all other entity-pages, too.
I personally think that clicking on 'more' and only getting one additional info like one sentence could be disappointing to the user.

**Comment by BernhardHumm** [comment]
Correction: please add as new requirement (prio low), replacing the old one:

Always fold “more” tabs when opening a page (all kinds of pages).

Reason: The focus should be on images, not on text. If the user wants more information he has to actively select “more”.

 

 

 

------------------------------------

 

 

Von: Humm, Bernhard, Prof. Dr. 
Gesendet: Freitag, 19. Juni 2020 09:28
An: 'hochschule-darmstadt/openartbrowser' <reply@reply.github.com>
Betreff: AW: [hochschule-darmstadt/openartbrowser] "more" tab unfolded when opening motif page (#394)

 

OK, then leave it the way it is.

 

 

 

------------------------------------

 

Von: Adrian Kailus [mailto:notifications@github.com] 
Gesendet: Donnerstag, 18. Juni 2020 14:06
An: hochschule-darmstadt/openartbrowser <openartbrowser@noreply.github.com <mailto:openartbrowser@noreply.github.com> >
Cc: Humm, Bernhard, Prof. Dr. <bernhard.humm@h-da.de <mailto:bernhard.humm@h-da.de> >; Author <author@noreply.github.com <mailto:author@noreply.github.com> >
Betreff: Re: [hochschule-darmstadt/openartbrowser] "more" tab unfolded when opening motif page (#394)

 

Sure it would be easy but is this the new requirement? Because at the moment it seems like a feature that the more-section is displayed when it has a small amount of content. This applies not only to the motif-page but for all other entity-pages, too.
I personally think that clicking on 'more' and only getting one additional info like one sentence could be disappointing to the user.
