### ISSUE TITLE
Naming conventions in ETL documentation

### ISSUE THREAD

**Issue by tilomi** [hochschule-darmstadt/openartbrowser#40]
**Is your feature request related to a problem? Please describe.**
Currently there are no naming conventions within the folder structure or the code files. It's rather a mix of camelCase or snake_case, but there is no restriction on what to use. Python provides  https://www.python.org/dev/peps/pep-0008/ for code naming conventions which i would suggest for all ETL script code (*.py, *.js). All folders and intermediate / created files should be named in snake_case because the majority is already named this way (for example: artworks_rank.json).

**Why do you want this feature? What goals should be achieved**
This feature will improve readability and also provides structure when the ETL is extended

**Describe the solution you'd like**
Described above.

**Describe acceptance criteria**
There are clear naming rules which are documented and can be tested with CI.

**Comment by JaGennis** [comment]
Maybe we should consider adapting the crawler code to PEP-8 as well

**Comment by tilomi** [comment]
The code part will be resolved by #172. I will refactor script names and folder names and close this ticket once its done.

**Comment by tilomi** [comment]
I mentioned all this here https://github.com/hochschule-darmstadt/openartbrowser/wiki/Developer-guide#coding-conventions-for-the-backend

**Comment by mxxbe** [comment]
Seems fixed - just re-open it if we were wrong
