### ISSUE TITLE
Fix absolute rank

### ISSUE THREAD

**Issue by mauamy** [hochschule-darmstadt/openartbrowser#402]
**Describe the bug**
Absolute rank is a measure for the amount of available metadata. Currently the absolute rank values on artworks are wrong / bugged. For example. `/artwork/Q64350351` has the absolute rank of **9000** but only got ~6 tags for display. So this high value should be completely unjustified.

**To Reproduce**
1. Inspect the `All Artworks` page
2. Check out the first few artworks and their displayed tags related to their absolute rank

**Expected behavior**
The absolute rank should be calculated in a reasonable and correct way.

TODO: Precisely describe the correct way to calculate the absolute rank. (@BernhardHumm)

**Comment by tilomi** [comment]
#5 and #72 already exist

**Comment by EeveesEyes** [comment]
sure but this is a bug, so this is no duplicate, i think. I could have linked them though :)

**Comment by BernhardHumm** [comment]
Description of ranking logic in 
https://github.com/hochschule-darmstadt/openartbrowser/wiki/System-architecture#ranking

**Comment by mauamy** [comment]
This bug is a result of the length attribute in the artwork object. This length attribute shadows the internal length attribute and therefore the intended iteration done by lodash fails due to the usage of the dimension length instead of the object length.
Because this is most likely a language specific issue, #72 will get rid of this bug.

**Comment by EeveesEyes** [comment]
> This bug is a result of the length attribute in the artwork object. This length attribute shadows the internal length attribute and therefore the intended iteration done by lodash fails due to the usage of the dimension length instead of the object length.
> Because this is most likely a language specific issue, so implementing the ranking in python (issue #72) will get rid of this bug.

This could be the best bug in 2020, if not in all years to come.

![tmp](https://user-images.githubusercontent.com/28682931/85444209-66a28100-b592-11ea-9166-b082b4d887e1.png)

**Comment by tilomi** [comment]
fixed with #408
