### ISSUE TITLE
Include main motifs on the artwork page

### ISSUE THREAD

**Issue by mxxbe** [hochschule-darmstadt/openartbrowser#409]
**Is your feature request related to a problem? Please describe.**
Issue #292 described changes that would later turn out to be two features with quite different requirements.
This issue shall handle the requirements that only concern the main motifs.

**Why do you want this feature? What goals should be achieved**
Increases the learning effect and fun in using openArtBrowser through the display of new information.

**Describe the solution you'd like**
The main motif attribute, that is already present in the etl process, shall be integrated in an informative way.

**Describe acceptance criteria**
- additional category 'main motif' above the 'motifs' on the artwork page
- integrate main motifs into the `related artworks by motif` tab at the bottom of the artwork page
- add an additional tab for `related artworks by main motif` at the bottom of the artwork page

**What effects does your proposed solution have**
We display the new information, and also allow the user to find artworks that are related to the current artwork by the same main motif (opposed to just any motif displayed in both artworks - which is more concise)

**Additional context**
There have already been pull requests (#347 #336 ) that integrated the first 2 acceptance criteria - the main todo at this point is adding the main motif tab.

**Comment by BernhardHumm** [comment]
Another small point:

Change the label in the motif tab to plural form (“motifs”), analogous to the detail page 

(for all languages)

 

 

 

------------------------------------

 

 

Von: Jenja Schurse [mailto:notifications@github.com] 
Gesendet: Mittwoch, 1. Juli 2020 12:09
An: hochschule-darmstadt/openartbrowser <openartbrowser@noreply.github.com>
Cc: Subscribed <subscribed@noreply.github.com>
Betreff: Re: [hochschule-darmstadt/openartbrowser] Include main motifs on the artwork page (#409)

 

Closed #409 <https://github.com/hochschule-darmstadt/openartbrowser/issues/409>  via #428 <https://github.com/hochschule-darmstadt/openartbrowser/pull/428> .
