### ISSUE TITLE
Missing entities-count

### ISSUE THREAD

**Issue by EeveesEyes** [hochschule-darmstadt/openartbrowser#417]
**Describe the bug**
On staging and life servers the complete number of available entity-items is not displayed. This might be because of the sloppy query i wrote in data.service#countEntityItems(). This query should be fixed.

**To Reproduce**
1. Go to openartbrowser.org/en/artists or any other entities-page
2. See missing number

**Expected behavior**
The number of all items of given type should be displayed

**Screenshots**
It should look like this, but the number is missing:
![tmp](https://user-images.githubusercontent.com/28682931/85630509-0c79ec80-b674-11ea-9aa1-a31f96dd77cb.png)

**Comment by tilomi** [comment]
maybe related to #435
