### ISSUE TITLE
Refactor Entities-Component into a Fetching-List-Component

### ISSUE THREAD

**Issue by mauamy** [hochschule-darmstadt/openartbrowser#422]
**Is your feature request related to a problem? Please describe.**
Currently there is no reusable component for continues fetching / loading of entities.

**Why do you want this feature? What goals should be achieved**
Implementing a shared component would reduce complexity and code duplication in other components.

**Describe the solution you'd like**
 Since the entities-component already implements this behavior it should be extracted from it into a shared fetching-list-component. 
In addition to the current implementation the fetching-list-component should implement a vertical paginator for easier navigation.

![tmp](https://user-images.githubusercontent.com/28662686/85717115-72568a80-b6ed-11ea-8c79-4b26f0a561af.png)

**Implementation**
The fetching of the entities (artworks, etc.) should be done by the parent component. Therefor the parent component needs to implement a callback function that re-fetches new entities as soon as the fetching-list-component "triggers". This could either be done by passing a function as `input` into the fetching-list-component or by defining an `output` event inside the fetching-list-component and catching the event in the parent component.

For the implementation of the paginator it would be nice to use a GET parameter like `page` (
`openartbrowser.org/en/artworks?page=1`. If this is implemented by the fetching-list-component or the parent components needs to be determined.

**Describe acceptance criteria**
A reusable fetching-list-component (name may be changed) provides the functionality to continuously load entities (e.g. artworks) and provides a vertical paginator (like displayed above) for easier navigation. 

**What effects does your proposed solution have**
A shared an therefore reusable component would lead to less code duplication and complexity. Furthermore this component might become useful for different features of the site. For example it could replace the carousel-slider.

**Comment by EeveesEyes** [comment]
###Current Progress:
Currently the list is organized into pages, which contain items. Pages are fetched depending on the view-port, therefore the list of pages is not continuous (eg. pages =  [page1, page2, page6, page7, page8]).
- [ ] Paginator-component triggers fetching of list
- [ ] Scrolling up and down triggers fetching of list and change of paginator-component
- [ ] 

Fetching dependent on the view-port:
![image](https://user-images.githubusercontent.com/28682931/87654364-12d12500-c757-11ea-82d2-6b14545d428d.png)
