### ISSUE TITLE
Add additional classes to crawling process

### ISSUE THREAD

**Issue by EeveesEyes** [hochschule-darmstadt/openartbrowser#452]
**Is your feature request related to a problem? Please describe.**
This is related to #451 (not dependent). 

**Why do you want this feature? What goals should be achieved**
More data.

**Describe the solution you'd like**
Add the following classes: (tbd) prints, architecture (?)...

**Comment by EeveesEyes** [comment]
This lists all subclasses of Artwork (Q838948), which could give some inspiration. Q4502142 would be visual artwork
https://query.wikidata.org/#SELECT%20?s%20?desc%20WHERE%20%7B?s%20wdt:P279+%20wd:Q838948%20.OPTIONAL%20%7B?s%20rdfs:label%20?desc%20filter%20(lang(?desc)%20=%20%22en%22).%7D%7D
The problem with this is the vast variety of artworks, so we should probably create a selection of new types.

**Comment by BernhardHumm** [comment]
Use a SPARQL construct query to extract the entire Artwork (Q838948) hierarchy from Wikidata.

This file can then be opened and inspected in Protégé. We can then discuss possible subtrees to be included / excluded.

 

 

------------------------------------

 

Von: Adrian Kailus ***@***.***> 
Gesendet: Mittwoch, 14. April 2021 13:23
An: hochschule-darmstadt/openartbrowser ***@***.***>
Cc: Subscribed ***@***.***>
Betreff: Re: [hochschule-darmstadt/openartbrowser] Add additional types to crawling process (#452)

 

This lists all subclasses of Artwork (Q838948), which could give some inspiration. Q4502142 would be visual artwork
https://query.wikidata.org/#SELECT%20?s%20?desc%20WHERE%20%7B?s%20wdt:P279+%20wd:Q838948%20.OPTIONAL%20%7B?s%20rdfs:label%20?desc%20filter%20(lang(?desc)%20=%20%22en%22).%7D%7D
The problem with this is the vast variety of artworks, so we should probably create a selection of new types.

**Comment by EeveesEyes** [comment]
The first step would include a restructuring of the crawling process and to modify the query so that the result set includes all subsets of type 'artwork':

- [ ] All new 'sub' types of 'artwork' should be matched by the sparql query, so no further merging of artwork types is necessary
- [ ] The only constraint for an item should be an image (as is already the case)
