### ISSUE TITLE
Timeline items not accessible

### ISSUE THREAD

**Issue by EeveesEyes** [hochschule-darmstadt/openartbrowser#462]
**Describe the bug**
Access of the first items in a timeline is sometimes not possible. 

**To Reproduce**
1. Go to https://openartbrowser.org/en/movement/Q1277524
2. Try to use the timeline slider to access the first items in the timeline
3. See error

**Expected behavior**
The user should be able to navigate to all items in the timeline using each of the two options (buttons and slider).

**Additional context**
Maybe the minimal value of the slider is set to a wrong value?

**Comment by SpaceDave42** [comment]
Issue closed as it is already merged
