### ISSUE TITLE
Fulltext-search part 2, fetching list 

### ISSUE THREAD

**Issue by EeveesEyes** [hochschule-darmstadt/openartbrowser#506]
**Reason (Why?)**
To achieve results quickly, the search should be implemented in parts. This is the second part of three (see related issues)

**Solution (What?)**
In the second part of the new full text search the search result set should be presented in the fetching list component to enable the user to scroll through the result set. From Part 1 (#505) each type already has its query which should be passed to the fetching list component.

![image](https://user-images.githubusercontent.com/28682931/121081792-7b951600-c7dd-11eb-9f80-da28512160b9.png)

**Out of scope**
- modifications to the query
- filters

**Relation to other Issues**
Parent: #199
Part 1: #505 
Part 3: #507 

**Acceptance criteria**
The user should be able to scroll through the result set and jump to specific pages.

**Comment by vinoroidski** [comment]
@EeveesEyes @tpachmann @FabioBurillo 

Nach unsere Diskussion, wollen wir in irgendeinen Form (Icons, Hover, usw.) unter "All" Tab darstellen was für ein Typ dieses Element hat.
