### ISSUE TITLE
Display count of data sets for results

### ISSUE THREAD

**Issue by jschurse** [hochschule-darmstadt/openartbrowser#56]
**Is your feature request related to a problem? Please describe.**
When searching for an artist or a movement at the openartbrowser you get a resultpage, but the total number of data sets is not shown.

**Why do you want this feature? What goals should be achieved**
The user should have an idea how many data sets can be viewed.

**Describe the solution you'd like**
When results are being displayed the number of total results shall be displayed
![image](https://user-images.githubusercontent.com/12964877/69325978-536db280-0c4b-11ea-815b-6687fbc6eff5.png)

**Describe acceptance criteria**
On all result pages the number of total results shall be displayed.

**What effects does your proposed solution have**
The information is already available. Elasicsearch returns the number of total results in 
`response.hits.total.value`

**Additional context**
Could be visualized like this:
![image](https://user-images.githubusercontent.com/12964877/69327287-9466c680-0c4d-11ea-9a6c-109393334891.png)

**Comment by mxxbe** [comment]
#118  solves the first part - we will have to discuss if the second part will be developed
