### ISSUE TITLE
Custom scroll bar

### ISSUE THREAD

**Issue by EeveesEyes** [hochschule-darmstadt/openartbrowser#561]
**Reason (Why?)**
The default scroll bar with the grey box background is not beautiful. 

**Solution (What?)**
CSS allows customization of the scroll bar. Create such a custom search bar.

**Relation to other Issues**
Solution of einander-helfen.org : https://github.com/hochschule-darmstadt/einander-helfen/issues/399

**Acceptance criteria**
Beautified scroll bar.

**Comment by GiotisK** [comment]
I'm new to contributing and I would like to fix this issue. I downloaded the repo and I have already customized the sidebar.

**Comment by EeveesEyes** [comment]
@GiotisK your changes are now deployed to the live server https://openartbrowser.org

**Comment by GiotisK** [comment]
That's great. I will look for more easy issues that I can solve in this project 👍
