### ISSUE TITLE
Matomo changes

### ISSUE THREAD

**Issue by EeveesEyes** [hochschule-darmstadt/openartbrowser#564]
**Reason (Why?)**
Currently, the legal basis for our matomo tracking is kind of uncertain. Some actions are required to resolve this uncertainty.

**Solution (What?)**
- on the data-protection page, change the IP sentence to: "Anonymisierte IP-Adressen indem die letzten 2 bytes entfernt werden (also 198.51.xxx.xxx anstatt 198.51.100.54)"
- synchronize matomo settings with einander-helfen
- remove opt-out box from data-protection page (because it uses cookies)

**Comment by vinoroidski** [comment]
- synchronize matomo settings with einander-helfen (DONE - see screenshot below)

![image](https://user-images.githubusercontent.com/6040299/124104467-98321000-da62-11eb-9e41-31aad3b0b00e.png)
