### ISSUE TITLE
Add a timeline component to artist and movement pages

### ISSUE THREAD

**Issue by EeveesEyes** [hochschule-darmstadt/openartbrowser#65]
**Is your feature request related to a problem? Please describe.**
A unprofessional user has no overview of the relation of artworks and active artists to time periods.

**Why do you want this feature? What goals should be achieved**
Teach users the context of time and art. 

**Describe the solution you'd like**
A optional alternative to the slider-component, which displays artworks on a timeline, is animated and scrollable and can be used to navigate _through time_. 
See Additional context for mockups.

**Describe acceptance criteria**
A timeline component is displayed on the page and can be used to navigate. 
So using the timeline to navigate changes the related artworks accordingly and it is possible to
skip to the next/previous movement.

*How, if and how precise the time periods of the different movements and the related order of these movements can be acquired needs to be determined. Therefore it is currently unclear how the exact navigations through the different movements will work.*

**Describe alternatives you've considered**
A general overview of timelines and movements. Probably both.

**What effects does your proposed solution have**
We need to crawl more fields of the wikidata dataset and change the model. 

_This issue is closely coupled to issue #69_

**Additional context**
![Timeline_Movement_2_ArtworksSwitch](https://user-images.githubusercontent.com/28682931/69332659-6c7c6080-0c57-11ea-94bb-a261a4c46cea.png)

**Comment by EeveesEyes** [comment]
Continuous timeline with fixed amount of labels (about 7 +/- 2) in reasonable steps (1830,1840..).
Display 2 items with inception <= selected value and 2 items with inception > selected value.
Always display 4 items.
Display Birth and Death of artist.
Display no timeline if there are less than 4 items available.

**Comment by BernhardHumm** [comment]
In the movement timeline, you could consider to also display artists in addition to artworks (if artists have an image). Images of artists should be displayed differently (oval) than images of artworks (rectangular). They could be  lined in according to their birthdate; under the image I would display birthdate and death date, e.g., 1523-1584.

 

           Bernhard Humm

 

 

Von: Adrian Kailus [mailto:notifications@github.com] 
Gesendet: Donnerstag, 28. November 2019 11:56
An: hochschule-darmstadt/openartbrowser <openartbrowser@noreply.github.com>
Cc: Subscribed <subscribed@noreply.github.com>
Betreff: Re: [hochschule-darmstadt/openartbrowser] Add a timeline component to artist and movement pages (#65)

 

Continuous timeline with fixed amount of labels (about 7 +/- 2) in reasonable steps (1830,1840..).
Display 2 items with inception <= selected value and 2 items with inception > selected value.
Always display 4 items.
Display Birth and Death of artist.
Display no timeline if there are less than 4 items available.

**Comment by mauamy** [comment]
TODOs:
- [ ] CSS Styling: Carousel Buttons, etc. 
- [ ] Refactor and generalize timeline component
- [ ] Revert slider component changes (keep stable height)
- [ ] Two tabs for timeline and overview 
- [ ] Add artists to carousel items based on productive/active period (maybe just the first artwork) **tbd.**

**Comment by EeveesEyes** [comment]
- [ ] Decide if timeline or carousel component is shown per default

**Comment by BernhardHumm** [comment]
Timeline should be default

 

           Bernhard Humm

 

------------------------------------

 

 

Von: Adrian Kailus [mailto:notifications@github.com] 
Gesendet: Donnerstag, 12. Dezember 2019 11:59
An: hochschule-darmstadt/openartbrowser <openartbrowser@noreply.github.com>
Cc: Humm, Bernhard, Prof. Dr. <bernhard.humm@h-da.de>; Comment <comment@noreply.github.com>
Betreff: Re: [hochschule-darmstadt/openartbrowser] Add a timeline component to artist and movement pages (#65)

 

*	[ ] Decide if timeline or carousel component is shown per default

**Comment by EeveesEyes** [comment]
- [ ] Catch loading errors
