### ISSUE TITLE
Uniformly code formatting

### ISSUE THREAD

**Issue by jschurse** [hochschule-darmstadt/openartbrowser#67]
**Is your feature request related to a problem? Please describe.**
In the last weeks we had many pull requests with changes on files resulting from differently formatted source Code. This is a problem because the reviewers see many changes which could be omitted if we all would use the same Code formatting settings.

**Why do you want this feature? What goals should be achieved**
Code reviews shall be more simple, less changes would be commited.

**Describe the solution you'd like**
A config for the used IDE's (JetBrains, VSC, etc.) with well defined style rules.

**Describe acceptance criteria**
Committed code shall be formatted uniformly

**Describe alternatives you've considered**
A githook pre commit could reformat code with the defined Style rules before committing.

**What effects does your proposed solution have**
Less noise in commit history, less changes on pull requests.

**Comment by tilomi** [comment]
#40 related
