### ISSUE TITLE
Movement overview timeline on start page

### ISSUE THREAD

**Issue by mauamy** [hochschule-darmstadt/openartbrowser#69]
**Is your feature request related to a problem? Please describe.**
The user has no overview of the different movements an their chronological order.

**Why do you want this feature? What goals should be achieved**
Teach users the context of time and art movements.

**Describe the solution you'd like**
Adding an overview timeline containing (the most important) movements which are not a sub-movement to the start page.
This information can be acquired by the wikidata dataset. An empty *is part of* field indicates
that the movement is not a sub-movement itself.  

In the future it might be possible to add more movements (even sub-movements). But this depends on how this will blow up the start page.

**Describe acceptance criteria**
A timeline on the start page shows a few different important movements in chronological order.

**Describe alternatives you've considered**
None

**What effects does your proposed solution have**
We need to crawl more fields of the wikidata dataset and change the model.

*This issue is closely coupled to issue #65*.
Therefore the newly required data should be equal for both features.

**Additional context**
![Timeline_Movement_overview](https://user-images.githubusercontent.com/28682931/69335000-2f669d00-0c5c-11ea-8fa7-e68475283d69.png)

**Comment by EeveesEyes** [comment]
This is not even started yet
