### ISSUE TITLE
Merge artworks in crawler

### ISSUE THREAD

**Issue by JaGennis** [hochschule-darmstadt/openartbrowser#74]
**Is your feature request related to a problem? Please describe.**
So far, the artworks have been merged with JavaScript. We dont want to use JS anymore.

**Why do you want this feature? What goals should be achieved**
Clearer code

**Describe the solution you'd like**
Generate artworks.json in the crawler.

**Describe acceptance criteria**
If the same file is created by the crawler as by the JS script.

**Describe alternatives you've considered**
Keep JS?

**What effects does your proposed solution have**
Clearer code overview.

**Additional context**
...

**Comment by jschurse** [comment]
Feature has been merged!
