### ISSUE TITLE
Integrate usage analytics

### ISSUE THREAD

**Issue by lbucas** [hochschule-darmstadt/openartbrowser#84]
**Is your feature request related to a problem? Please describe.**
To have an Idea how users utilze the openartbrowser we need metrics.
It would be good to know which pages are being consulted and on which path the user navigates the app.

**Why do you want this feature? What goals should be achieved**
The feature should give us deeper insights into the following topics:
- Which artworks, artists & movements are the most popular among users This information can be used for the ranking algorithms.
- Which features are used.
- How long users stay on the site.

**Describe the solution you'd like**
The integration of an analytics tool which collects these metrics for as and presents them graphically.

**Describe acceptance criteria**
- An analytics tool is integrated.
- Each page call and navigation is being protocolled.
- We can determine how long a user uses which page.
- The data privacy statement is adapted accordingly.

**Describe alternatives you've considered**
We could log the requests to Elasticsearch.

**What effects does your proposed solution have**
The user is beeing tracked, data privacy statement should be updated.

**Comment by lbucas** [comment]
I already created the Google Account openartbrowser@gmail.com. I will use it for G-Analytics integration.

**Comment by BernhardHumm** [comment]
Please leave credentials accessible in file share.

 

           Bernhard Humm

 

 

 

Von: Lucas Bergmann [mailto:notifications@github.com] 
Gesendet: Donnerstag, 28. November 2019 11:47
An: hochschule-darmstadt/openartbrowser <openartbrowser@noreply.github.com>
Cc: Subscribed <subscribed@noreply.github.com>
Betreff: Re: [hochschule-darmstadt/openartbrowser] Integrate usage analytics (#84)

 

I already created the Google Account openartbrowser@gmail.com <mailto:openartbrowser@gmail.com> . I will use it for G-Analytics integration.

**Comment by lbucas** [comment]
I have created a credentials file in the _Knowledge Management_ section in our NextCloud. Once integrated, you will be able to view the statistics here: https://analytics.google.com/analytics/web/ .

**Comment by BernhardHumm** [comment]
Better move to „implementation“ folder

 

           Bernhard Humm

 

 

 

Von: Lucas Bergmann [mailto:notifications@github.com] 
Gesendet: Donnerstag, 28. November 2019 17:30
An: hochschule-darmstadt/openartbrowser <openartbrowser@noreply.github.com>
Cc: Humm, Bernhard, Prof. Dr. <bernhard.humm@h-da.de>; Comment <comment@noreply.github.com>
Betreff: Re: [hochschule-darmstadt/openartbrowser] Integrate usage analytics (#84)

 

I have created a credentials file in the Knowledge Management section in our NextCloud. Once integrated, you will be able to view the statistics here: https://analytics.google.com/analytics/web/ .

**Comment by lbucas** [comment]
I am trying to use [Angulartics2](https://github.com/angulartics/angulartics2) module as a wrapper for GAnalytics, but I ran into some strange errors while compiling:

`./node_modules/angulartics2/gtm/fesm5/angulartics2-gtm.js 103:51-69
"export 'ɵɵdefineInjectable' was not found in '@angular/core'`

Has anybody seen this before?

**Comment by lbucas** [comment]
I am struggling with the integration of the [google analytics types](https://www.npmjs.com/package/@types/google.analytics). I am using it in the analytics service:
```javascript
/// <reference types="@types/google.analytics" />
import {AnalyticsProperty} from '../../../environments/environment_analytics';

export const Analytics = {
  options: {
    pageTracking: {
      clearQueryParams: true,
    }
  },
  setTrackingId: () => {
    ga('create', AnalyticsProperty.trackingId, 'none');
  }
};
``` 

It works in the IDE, but the tests fail with

`ga is not defined`

@jschurse do you know how to solve this?

**Comment by jschurse** [comment]
According to the documentation of the plugin this should be done in a script block in the initial html:
https://github.com/angulartics/angulartics2/tree/d1d75ce2e05ae13fbce7aab92520359fc17ddc37/src/lib/providers/ga

**Comment by lbucas** [comment]
Matomo is installed and integrated. Usage on the staging server already gets tracked. 

Go to https://openartbrowser.org/api/analytics to see the result. Credentials are stored in the Implementation folder in the nextcloud.
