### ISSUE TITLE
Mobile View on Landing Page

### ISSUE THREAD

**Issue by marvinseith** [hochschule-darmstadt/openartbrowser#86]
**Is your feature request related to a problem? Please describe.**
When the Home Page is opened on a mobile device, it is really hard to navigate through related Artworks. All Artworks are displayed under each other with arrows which need to be clicked to get new pictures. Those are very difficult to find.

**Why do you want this feature? What goals should be achieved**
The displayed pictures should be replaced with a gallery type slider to navigate, because it's more user friendly.

**Describe the solution you'd like**
Replace the pictures, displayed under each other with arrows that need to be pressed to cycle through, with a intuitive slider gallery for the pictures.

**Describe acceptance criteria**
The user can cycle through related artworks through a slider on a mobile device.

**What effects does your proposed solution have**
Needs to be restricted to mobile devices.

**Comment by xcaverxiii** [comment]
You mean almost everyone else page but not at the Home page

**Comment by xcaverxiii** [comment]
Is it ok to show only 1 image at the same time when is mobile ?

**Comment by marvinseith** [comment]
> 
> 
> You mean almost everyone else page but not at the Home page

correct, sorry my bad.



> 
> 
> Is it ok to show only 1 image at the same time when is mobile ?

thats what i would think, but not sure

**Comment by xcaverxiii** [comment]
is merged into staging
