### ISSUE TITLE
Mobile View Burger Menu

### ISSUE THREAD

**Issue by marvinseith** [hochschule-darmstadt/openartbrowser#87]
**Is your feature request related to a problem? Please describe.**
When the burger menu is clicked on mobile, the design shifts.

**Why do you want this feature? What goals should be achieved**
Design should stay the same for user experience.

**Describe the solution you'd like**
Fix the css, to not move the burger menu when clicked on mobile.

**Comment by xcaverxiii** [comment]
This CSS code must be added.
`.dropdown.show .dropdown-toggle {
    text-align: center;
}`

**Comment by xcaverxiii** [comment]
is merged into staging
