### ISSUE TITLE
Related Arwork Tag Menu on Mobile 

### ISSUE THREAD

**Issue by marvinseith** [hochschule-darmstadt/openartbrowser#88]
**Is your feature request related to a problem? Please describe.**
The display of the tags on the related artwork on mobile styling is not displayed with correct margins in the columns.

**Why do you want this feature? What goals should be achieved**
The Tags with corresponding icons should all be displayed with the same margins.

**Describe the solution you'd like**
Fix the css to display the tags correctly on mobile.

**Comment by xcaverxiii** [comment]
@media (max-width: 575px) {
    .nav-tabs .nav-item { width: 100%; }
}

**Comment by xcaverxiii** [comment]
is merged into staging
