### ISSUE TITLE
Aggregation to display movements from pictures to their artists

### ISSUE THREAD

**Issue by marvinseith** [hochschule-darmstadt/openartbrowser#89]
**Is your feature request related to a problem? Please describe.**
Display the corresponding movements from the pictures of an artist under the movements of an artist.

**Why do you want this feature? What goals should be achieved**
To show all movements of the painted pictures on the artist page.

**Comment by BernhardHumm** [comment]
This is not simply a display issue but a data enhancement issue. 

It should be implemented in the ETL process. The client should not be affected.

 

           Bernhard Humm

 

 

 

Von: Marvin Seith [mailto:notifications@github.com] 
Gesendet: Donnerstag, 28. November 2019 12:27
An: hochschule-darmstadt/openartbrowser <openartbrowser@noreply.github.com>
Cc: Subscribed <subscribed@noreply.github.com>
Betreff: [hochschule-darmstadt/openartbrowser] Aggregation to display movements from pictures to their artists (#89)

 

Is your feature request related to a problem? Please describe.
Display the corresponding movements from the pictures of an artist under the movements of an artist.

Why do you want this feature? What goals should be achieved
To show all movements of the painted pictures on the artist page.

**Comment by EeveesEyes** [comment]
Implemented by #302
