### ISSUE TITLE
Add angular i18n functionality 

### ISSUE THREAD

**Issue by xcaverxiii** [hochschule-darmstadt/openartbrowser#9]
**Is your feature request related to a problem? Please describe.**
I can't speak english. I want to visit the website in my native language. 

**Why do you want this feature? What goals should be achieved**
Translate the website in mutli languages. Show static labels and content in different languages. 

**Describe the solution you'd like**
Implementing the angular i18n feature. Change all static labels by the i18n functionality.  
Implement different content fetches for each language. Specify the language for content fetching for each language build.

**Describe acceptance criteria**
All labels are translated by i18n.  
You can add some new translation file to translate the website in a new language. 

**Describe alternatives you've considered**

Translate all static labels by an cloud translation provider at runtime. 
https://medium.com/@DenysVuika/simple-i18n-support-for-your-angular-apps-6138a47eb2a9
https://github.com/ngx-translate/core

**What effects does your proposed solution have**
Please describe what effects and consequences your proposed solution has on other parts of the code and on the future development

All static labels should set by i18n. 
The database should provide data in mutliple languages.  

**Additional context**
https://angular.io/guide/i18n

**Comment by xcaverxiii** [comment]
Add translation for dynamic labels like **Search Placeholder**.
=> Add translations for any language in the translation file. Get the value dynamic by runtime.

**Comment by xcaverxiii** [comment]
_Impess_, _About_ and _Data Protection_ page not translated just now.

**Comment by xcaverxiii** [comment]
To create a tranlated xlf file i use the tool TinyTranlator:
https://martinroob.github.io/tiny-translator/en

User Manual can be find in the Wiki:
https://github.com/martinroob/tiny-translator

**Comment by xcaverxiii** [comment]
Some bug appear by translating in other languages.
The size of the label field is set static, so the label will be gone under the value field.

![image](https://user-images.githubusercontent.com/25961416/68084824-26439680-fe3b-11e9-96ce-c61b68ceb414.png)

This can be solved by set the labels in a table with dynamic with for the first column.

**Comment by xcaverxiii** [comment]
Added wiki documentation how to add a new label and how to add a new whole lanugage.

**Comment by BernhardHumm** [comment]
Ich kann diesen Text nicht verstehen.

 

 

Viele Grüße

           Bernhard Humm

 

 

Von: Xcaver [mailto:notifications@github.com] 
Gesendet: Sonntag, 3. November 2019 13:12
An: hochschule-darmstadt/openartbrowser <openartbrowser@noreply.github.com>
Cc: Subscribed <subscribed@noreply.github.com>
Betreff: Re: [hochschule-darmstadt/openartbrowser] Add angular i18n functionality (#9)

 

Some bug appear by translating in other languages.
The size of the label field is set static, so the label will be gone under the value field.

 <https://user-images.githubusercontent.com/25961416/68084824-26439680-fe3b-11e9-96ce-c61b68ceb414.png> 

This can be solved by set the labels in a table with dynamic with for the first column.

**Comment by BernhardHumm** [comment]
Es soll doch nichts automatisch übersetzt werden.

Sie können natürlich zum Anlegen der Übersetzungen ein Übersetzungsprogramm verwenden, aber die Übersetzungen sollen statisch abgelegt und qualitätsgesichert werden.

 

 

Viele Grüße

           Bernhard Humm

 

------------------------------------

Prof. Dr. Bernhard Humm

Geschäftsführender Direktor, Institut für angewandte Informatik Darmstadt (aiDa)

Vorsitzender Promotionsausschuss, Promotionszentrum Angewandte Informatik

h_da Hochschule Darmstadt - University of Applied Sciences, fbi Fachbereich Informatik 

Schöfferstr. 8b, D-64295 Darmstadt

Tel: +49 6151 16 38494, Fax: +49 6151 16 38935, Home Office: +49 6031 6714726

 <mailto:bernhard.humm@h-da.de> bernhard.humm@h-da.de, https://fbi.h-da.de/personen/personenseiten/bernhard-humm/

 

 

Von: Xcaver [mailto:notifications@github.com] 
Gesendet: Sonntag, 3. November 2019 13:08
An: hochschule-darmstadt/openartbrowser <openartbrowser@noreply.github.com>
Cc: Subscribed <subscribed@noreply.github.com>
Betreff: Re: [hochschule-darmstadt/openartbrowser] Add angular i18n functionality (#9)

 

To create a tranlated xlf file i use the tool TinyTranlator:
https://martinroob.github.io/tiny-translator/en

User Manual can be find in the Wiki:
https://github.com/martinroob/tiny-translator

**Comment by BernhardHumm** [comment]
Impressum und Datenschutzerklärung bitte nicht übersetzen, da juristische Texte und für Deutschland gültig. Lediglich in der Überschrift in allen Sprachen anzeigen, dass dieser Text in deutsch ist. 

 

 

Viele Grüße

           Bernhard Humm

 

------------------------------------

Prof. Dr. Bernhard Humm

Geschäftsführender Direktor, Institut für angewandte Informatik Darmstadt (aiDa)

Vorsitzender Promotionsausschuss, Promotionszentrum Angewandte Informatik

h_da Hochschule Darmstadt - University of Applied Sciences, fbi Fachbereich Informatik 

Schöfferstr. 8b, D-64295 Darmstadt

Tel: +49 6151 16 38494, Fax: +49 6151 16 38935, Home Office: +49 6031 6714726

 <mailto:bernhard.humm@h-da.de> bernhard.humm@h-da.de, https://fbi.h-da.de/personen/personenseiten/bernhard-humm/

 

 

Von: Xcaver [mailto:notifications@github.com] 
Gesendet: Sonntag, 3. November 2019 12:19
An: hochschule-darmstadt/openartbrowser <openartbrowser@noreply.github.com>
Cc: Subscribed <subscribed@noreply.github.com>
Betreff: Re: [hochschule-darmstadt/openartbrowser] Add angular i18n functionality (#9)

 

Impess, About and Data Protection page not translated just now.

**Comment by BernhardHumm** [comment]
Nein, Labels nicht dynamisch zur Laufzeit übersetzen. 

QS!

 

 

Viele Grüße

           Bernhard Humm

 

------------------------------------

Prof. Dr. Bernhard Humm

Geschäftsführender Direktor, Institut für angewandte Informatik Darmstadt (aiDa)

Vorsitzender Promotionsausschuss, Promotionszentrum Angewandte Informatik

h_da Hochschule Darmstadt - University of Applied Sciences, fbi Fachbereich Informatik 

Schöfferstr. 8b, D-64295 Darmstadt

Tel: +49 6151 16 38494, Fax: +49 6151 16 38935, Home Office: +49 6031 6714726

 <mailto:bernhard.humm@h-da.de> bernhard.humm@h-da.de, https://fbi.h-da.de/personen/personenseiten/bernhard-humm/

 

 

Von: Xcaver [mailto:notifications@github.com] 
Gesendet: Sonntag, 3. November 2019 11:37
An: hochschule-darmstadt/openartbrowser <openartbrowser@noreply.github.com>
Cc: Subscribed <subscribed@noreply.github.com>
Betreff: Re: [hochschule-darmstadt/openartbrowser] Add angular i18n functionality (#9)

 

Add translation for dynamic labels like Search Placeholder.
=> Add translations for any language in the translation file. Get the value dynamic by runtime.

**Comment by jschurse** [comment]
> Some bug appear by translating in other languages.
> The size of the label field is set static, so the label will be gone under the value field.
> 
> ![image](https://user-images.githubusercontent.com/25961416/68084824-26439680-fe3b-11e9-96ce-c61b68ceb414.png)
> 
> This can be solved by set the labels in a table with dynamic with for the first column.

It seems like the overlapping labels come from this styling directive
```
.info[_ngcontent-lrl-c11] {
    margin-left: -2em;
}
```
which moves the details 2em to the left and thus over the labels.

Without this styling directive it would be displayed like this:
![image](https://user-images.githubusercontent.com/12964877/68114004-5a7b8d80-fef5-11e9-882b-ce73e878ed02.png)

**Comment by xcaverxiii** [comment]
> It seems like the overlapping labels come from this styling directive
> 
> ```
> .info[_ngcontent-lrl-c11] {
>     margin-left: -2em;
> }
> ```

Ohh yeah, but with a width from 1100px there is always some overlapping:

![image](https://user-images.githubusercontent.com/25961416/68142698-3e491200-ff30-11e9-8c0f-e533056510bd.png)

One raw has always `col-md-3` for the label and `col-md-9` for the content. Maybe the label field must be wider, or that's the ideal case for a table, isn´t it?

**Comment by xcaverxiii** [comment]
> Es soll doch nichts automatisch übersetzt werden. Sie können natürlich zum Anlegen der Übersetzungen ein Übersetzungsprogramm verwenden, aber die Übersetzungen sollen statisch abgelegt und qualitätsgesichert werden.

This isn´t an automatic translation. All translated values will be stored in xlf files. But these files are quite hard to read, so there is an tool to make is easier to create an xlf file on a nother language. 
These xlf files will be stored in the project.

**Comment by xcaverxiii** [comment]
> Impressum und Datenschutzerklärung bitte nicht übersetzen, da juristische Texte und für Deutschland gültig. Lediglich in der Überschrift in allen Sprachen anzeigen, dass dieser Text in deutsch ist.

Okey, what about the 'About' page?

**Comment by xcaverxiii** [comment]
> Nein, Labels nicht dynamisch zur Laufzeit übersetzen.
Not translating the value by runtime, only dynamic fetching the translated value by runtime.
Today the different placeholder will be exchanged during the runtime too...
```
  /** String value binding the placeholder in the searchbar */
  placeholderText: string;

  /** Array of all placeholder values */
  placeholderArray: string[] = [
    'Search for something...',
    'Try "Mona Lisa"',
    'Try "Vincent van Gogh"',
    'Try "Renaissance"',
  ];

 ngAfterViewInit() {
    this.placeholderText = this.placeholderArray[0];
    const inv = interval(8000);
    inv.pipe(takeUntil(this.ngUnsubscribe)).subscribe((val) => this.changePlaceholdertext());
    this.cdRef.detectChanges();
  }

  /** Change the text inside the placeholder */
  public changePlaceholdertext() {
    ++this.counter;
    if (this.counter === this.placeholderArray.length) {
      this.counter = 0;
    }
    this.placeholderText = this.placeholderArray[this.counter];
  }
```

**Comment by BernhardHumm** [comment]
No, currently no translation service like Google translate or deepL is being called at runtime (and this should not be done)

 

 

Viele Grüße

           Bernhard Humm

 

 

Von: Xcaver [mailto:notifications@github.com] 
Gesendet: Montag, 4. November 2019 18:43
An: hochschule-darmstadt/openartbrowser <openartbrowser@noreply.github.com>
Cc: Humm, Bernhard, Prof. Dr. <bernhard.humm@h-da.de>; Comment <comment@noreply.github.com>
Betreff: Re: [hochschule-darmstadt/openartbrowser] Add angular i18n functionality (#9)

 

Nein, Labels nicht dynamisch zur Laufzeit übersetzen.
Not translating the value by runtime, only dynamic fetching the translated value by runtime.
Today the different placeholder will be exchanged during the runtime too...

  /** String value binding the placeholder in the searchbar */
 
  placeholderText: string;
 
 
 
  /** Array of all placeholder values */
 
  placeholderArray: string[] = [
 
    'Search for something...',
 
    'Try "Mona Lisa"',
 
    'Try "Vincent van Gogh"',
 
    'Try "Renaissance"',
 
  ];
 
 
 
 ngAfterViewInit() {
 
    this.placeholderText = this.placeholderArray[0];
 
    const inv = interval(8000);
 
    inv.pipe(takeUntil(this.ngUnsubscribe)).subscribe((val) => this.changePlaceholdertext());
 
    this.cdRef.detectChanges();
 
  }
 
 
 
  /** Change the text inside the placeholder */
 
  public changePlaceholdertext() {
 
    ++this.counter;
 
    if (this.counter === this.placeholderArray.length) {
 
      this.counter = 0;
 
    }
 
    this.placeholderText = this.placeholderArray[this.counter];
 
  }

**Comment by BernhardHumm** [comment]
I propose we leave the about page in English for the time being and translate it later if there is time (prio C)

 

 

Viele Grüße

           Bernhard Humm

 

 

 

Von: Xcaver [mailto:notifications@github.com] 
Gesendet: Montag, 4. November 2019 18:35
An: hochschule-darmstadt/openartbrowser <openartbrowser@noreply.github.com>
Cc: Humm, Bernhard, Prof. Dr. <bernhard.humm@h-da.de>; Comment <comment@noreply.github.com>
Betreff: Re: [hochschule-darmstadt/openartbrowser] Add angular i18n functionality (#9)

 

Impressum und Datenschutzerklärung bitte nicht übersetzen, da juristische Texte und für Deutschland gültig. Lediglich in der Überschrift in allen Sprachen anzeigen, dass dieser Text in deutsch ist.

Okey, what about the 'About' page?

**Comment by BernhardHumm** [comment]
OK, perfect

 

 

Viele Grüße

           Bernhard Humm

 

 

 

 

Von: Xcaver [mailto:notifications@github.com] 
Gesendet: Montag, 4. November 2019 18:33
An: hochschule-darmstadt/openartbrowser <openartbrowser@noreply.github.com>
Cc: Humm, Bernhard, Prof. Dr. <bernhard.humm@h-da.de>; Comment <comment@noreply.github.com>
Betreff: Re: [hochschule-darmstadt/openartbrowser] Add angular i18n functionality (#9)

 

Es soll doch nichts automatisch übersetzt werden. Sie können natürlich zum Anlegen der Übersetzungen ein Übersetzungsprogramm verwenden, aber die Übersetzungen sollen statisch abgelegt und qualitätsgesichert werden.

This isn´t an automatic translation. All translated values will be stored in xlf files. But these files are quite hard to read, so there is an tool to make is easier to create an xlf file on a nother language.
These xlf files will be stored in the project.

**Comment by xcaverxiii** [comment]
It is quite complex to translate properties with multiple text values.

There is no proper way to use translation strings outside a template:  
https://github.com/angular/angular/issues/11405

However, translating properties also can't use ICU expressions:
https://github.com/angular/angular/issues/21615

**Comment by istthabel** [comment]
The category labels (artist, movement, etc.) on the suggestion images on the home page are not yet translated. (See image)
![categoryTranslationMissing](https://user-images.githubusercontent.com/28310087/68802277-7c21f680-0612-11ea-84b0-f205bb99e921.jpg)

Do we want to leave this for later?

**Comment by xcaverxiii** [comment]
> The category labels (artist, movement, etc.) on the suggestion images on the home page are not yet translated. 
> Do we want to leave this for later?

No they should be translated, i just forgot them...
