### ISSUE TITLE
Detect broken video links

### ISSUE THREAD

**Issue by lbucas** [hochschule-darmstadt/openartbrowser#93]
**Is your feature request related to a problem? Please describe.**
Videos that we matched with our entities could be taken down from Youtube or we might have done mistakes when we collected the videos in the CSV file. The Openartbrowser will display a broken video in this case.

**Why do you want this feature? What goals should be achieved**
Broken videos should not be displayed.

**Describe the solution you'd like**
We could either detect broken links in the frontend or within the ETL process.

**Describe acceptance criteria**
Broken videos are not displayed anymore.

**Describe alternatives you've considered**
Manually delete wrong entries in the CSV.

**What effects does your proposed solution have**
Detection in the ETL process requires using the Youtube API.

**Comment by lbucas** [comment]
I would prefer detecting broken videos during the weekly ETL process for the following reasons:

- Even if the id is not valid, the embed YouTube endpoint will still deliver a response with status code 200. It is very difficult to detect if the link is valid with this approach.
- We could use the YouTube API in the frontend, but it is limited to 10000 requests per day.
- In the backend we could log the wrong Ids which would make it easier to find and fix them.

**Comment by lbucas** [comment]
There are some creative ways to detect broken IDs in the frontend, but they seem rather hacky and are not guaranteed to work reliably in the future.

https://gist.github.com/tonY1883/a3b85925081688de569b779b4657439b

**Comment by lbucas** [comment]
Checks during ETL have been implemented. We will add a check on the frontend using the videos preview picture. Disscussion can be found in #94

**Comment by jschurse** [comment]
I implemented the check as seen in the gist and refactored the video functionality to extract all the logic into it's own component.
@see #102

**Comment by lbucas** [comment]
Nice, thank you!
