### ISSUE TITLE
Make only image a required field when crawling artworks

### ISSUE THREAD

**Issue by tilomi** [hochschule-darmstadt/openartbrowser#95]
**Is your feature request related to a problem? Please describe.**
Currently label, image and so on are required fields. This should be reduced to only image as required field.

**Why do you want this feature? What goals should be achieved**
Hopefully more data for the openartbrowser.

**Describe the solution you'd like**
The changes are applied to the sparql-query in the crawler script and to the python code.

**Describe acceptance criteria**
We only have image as required field for artworks.

**Comment by BernhardHumm** [comment]
The change does not apply to the SPARQL query but only to the Python code.

 

           Bernhard Humm

 

 

Von: Tilo Michel [mailto:notifications@github.com] 
Gesendet: Freitag, 29. November 2019 09:49
An: hochschule-darmstadt/openartbrowser <openartbrowser@noreply.github.com>
Cc: Subscribed <subscribed@noreply.github.com>
Betreff: [hochschule-darmstadt/openartbrowser] Make only image a required field when crawling artworks (#95)

 

Is your feature request related to a problem? Please describe.
Currently label, image and so on are required fields. This should be reduced to only image as required field.

Why do you want this feature? What goals should be achieved
Hopefully more data for the openartbrowser.

Describe the solution you'd like
The changes are applied to the sparql-query in the crawler script and to the python code.

Describe acceptance criteria
We only have image as required field for artworks.

**Comment by tilomi** [comment]
The current query has to be adjusted just a little because artist (P170) is a required attribute at the moment. The rest stays the same.
From
```SPARQL
SELECT ?item ?sitelink WHERE {
  SERVICE wikibase:label { bd:serviceParam wikibase:language "[AUTO_LANGUAGE],en". }
  ?cls (wdt:P279*) wd:Q3305213.
  ?item wdt:P31 ?cls;
    wdt:P170 ?artist;
    wdt:P18 ?image.
}
```
To
```SPARQL
SELECT ?item ?sitelink WHERE {
  SERVICE wikibase:label { bd:serviceParam wikibase:language "[AUTO_LANGUAGE],en". }
  ?cls (wdt:P279*) wd:Q3305213.
  ?item wdt:P31 ?cls;
    wdt:P18 ?image.
}
```

Without the artist line i get about 2000 more entries:
* [Items with artists required](https://query.wikidata.org/#SELECT%20%28count%28distinct%20%3Fitem%29%20as%20%3Fcount%29%20WHERE%20%7B%0A%20%20SERVICE%20wikibase%3Alabel%20%7B%20bd%3AserviceParam%20wikibase%3Alanguage%20%22%5BAUTO_LANGUAGE%5D%2Cen%22.%20%7D%0A%20%20%3Fcls%20%28wdt%3AP279%2a%29%20wd%3AQ3305213.%0A%20%20%3Fitem%20wdt%3AP31%20%3Fcls%3B%0A%20%20%20%20wdt%3AP170%20%3Fartist%3B%0A%20%20%20%20wdt%3AP18%20%3Fimage.%0A%7D)

* [Items without artists required](https://query.wikidata.org/#SELECT%20%28count%28distinct%20%3Fitem%29%20as%20%3Fcount%29%20WHERE%20%7B%0A%20%20SERVICE%20wikibase%3Alabel%20%7B%20bd%3AserviceParam%20wikibase%3Alanguage%20%22%5BAUTO_LANGUAGE%5D%2Cen%22.%20%7D%0A%20%20%3Fcls%20%28wdt%3AP279%2a%29%20wd%3AQ3305213.%0A%20%20%3Fitem%20wdt%3AP31%20%3Fcls%3B%0A%20%20%20%20wdt%3AP18%20%3Fimage.%0A%7D)

**Comment by tilomi** [comment]
Merged in staging and currently running on the staging server
