### ISSUE TITLE
Refactor angular components 

### ISSUE THREAD

**Issue by xcaverxiii** [hochschule-darmstadt/openartbrowser#98]
**Is your feature request related to a problem? Please describe.**
No

**Why do you want this feature? What goals should be achieved**
Clean up the angular components. 

**Describe the solution you'd like**
Refactor component behavior. Maybe create some new components to reduce duplicate code.

**Describe acceptance criteria**
All is working as before.

**Describe alternatives you've considered**
Do nothing. 

**What effects does your proposed solution have**
None

**Additional context**

**Comment by jschurse** [comment]
Please have a look at https://github.com/hochschule-darmstadt/openartbrowser/pull/102
To implement the client-side check of availability for videos I extracted a video component.

**Comment by xcaverxiii** [comment]
is merged into staging
