### ISSUE TITLE
Enhance Youtube Video accessibility/ visibility

### ISSUE THREAD

**Issue by dernicolas** [hochschule-darmstadt/openartbrowser#99]
Since we implemented the video player within the "more" tab, the video can be pretty hidden on the regarding page. We also want to display more than just one video at the time.

With a button/ text that links to the video it should be possible to direct more people to the videos

An ideal solution would be a youtube logo with a link that refers the viewer towards the video by unfolding the more tab.

The goal is achieved when the video can be accessed smoothly by the viewer clicking on the link and having two videos of the entity and the regarding movement/artist/artwork

**Comment by dernicolas** [comment]
![Bildschirmfoto 2019-12-02 um 18 54 54](https://user-images.githubusercontent.com/33030683/69996548-920c4280-1552-11ea-8e5a-2a0efd38b539.png)

Added a Youtube Video Button that automatically opens to the more tab and move to the video element

**Comment by dernicolas** [comment]
Created a new branch and commit frontend changes on:
https://github.com/hochschule-darmstadt/openartbrowser/tree/enhancement/multiple-videos

@jschurse do you have an idea how can get a video of the entities regarding movement or artist if available? I actually tried it like in this Screenshot but it did not work out. The current code is comited to this branch.
![Bildschirmfoto 2019-12-09 um 19 10 11](https://user-images.githubusercontent.com/33030683/70461570-478e4700-1ab9-11ea-8966-e4679572496b.png)

**Comment by xcaverxiii** [comment]
@dernicolas 
instead of using two iframe elements in video.component.html
```
<iframe` *ngIf="videoExists && safeUrl" [src]='safeUrl' frameborder="0" allowfullscreen></iframe>

<iframe *ngIf="videoExists && safeUrl" [src]='safeUrl' frameborder="0" allowfullscreen></iframe>
```
You sould add multple video components in the artist.component.html, like descripted below  or something like that. Because the video components requieres an entity and and not specifically an artist. Movement ist also an entity like artist.
```
<app-video [entity]="artist"></app-video>
<app-video [entity]="artist.movement"></app-video>
```
In the video component it should be validated if the entity has an video property or not. If one entity has more then one video (if this could happen) then the video component must be refactored for these behavior.

**Comment by xcaverxiii** [comment]
Also i think, the link to the video should show the video title if this property is available in our system. Or just show the youtube logo, in my opinion.

**Comment by dernicolas** [comment]
> Also i think, the link to the video should show the video title if this property is available in our system. Or just show the youtube logo, in my opinion.
> 
> Btw, you had forgotten to add the issue id into the branch. Just for the next time ;)

This has already been resolved. It now shows only the Button.

**Comment by dernicolas** [comment]
@xcaverxiii when i use 

`<app-video [entity]="artist?.movements"></app-video>`

in the artist, I get `Object object` returned. Do you know a solution for this?

**Comment by xcaverxiii** [comment]
```artist?.movements``` is an array. So it will be an array of ```[object Object, object Object, ... ]```
You must but a foreach around them
```
<ng-template *ngFor="let movement of artist?.movements">
    <app-video [entity]="movement"></app-video>
</ng-tempalte>
```

**Comment by mxxbe** [comment]
@dernicolas is this issue still open, or can we close it?

**Comment by dernicolas** [comment]
It is finished. I will close it.
